### ISSUE TITLE
named conversations with fewer than 3 participants

### ISSUE THREAD

**Issue by jdiercks** [wireapp/wire#10]
I'd like to be able to create "named conversations" with just 1 one other person (maybe I've got a couple different topics/threads going with the same person and want to keep them separate) or even just a named conversation with only myself for stashing things that need to be accessible on all my devices. I can kludge it by creating a 3-person group and then deleting the other two people, but why shouldn't I be able to just create a named conversation with no members?

**Comment by wenbob** [comment]
yes, I need it too, and better with a conversation url.

**Comment by david-wire** [comment]
Thanks for the note. This is not planned at this stage, but thanks for the suggestion.

We're pleased to say that we have heard from many of our users about specific features that they would like to have. We are taking users' desired features very much into account in our planning, and we aim to get new features out as quickly as we can.

**Comment by alugarius** [comment]
I am also for that ability

**Comment by wmengli** [comment]
Hi, unfortunately this is still not planned at the moment.
We will close this for now and track it in our feature request system instead.
Thank you for your suggestion and feel free to contact us for other questions.

Best wishes,
Wire Support Team
