### ISSUE TITLE
Security concerns by Tina Membe

### ISSUE THREAD

**Issue by EgbertW** [wireapp/wire#102]
In a discussion about secure messengers, I was referred to the objections written by TIna Membe:

https://medium.com/@pepelephew/a-look-at-how-private-messengers-handle-key-changes-5fd4334b809a

This has strong objections to the handling of key chances in Wire, relating to multiple keys per user and issues when a user removes the app. This links to another article:

https://medium.com/@pepelephew/how-to-intercept-all-wire-voice-and-video-calls-13da1246675c

This objects to the unencrypted nature and lack of certificate pinning in the key exchange for voice calling. And to the fact that Wire is advertised as being Swiss-based while the servers are running on a Amazon (US) owned server in Ireland.

I'm creating this issue to check if and how these issues have been addressed so far. Or if these issues are incorrect in any way.

I saw the helpful issue https://github.com/wireapp/wire/issues/95 that relates to multiple keys per user which sounds like a good solution.

Any thoughts?

**Comment by raphaelrobert** [comment]
The first blog post is an inaccurate representation of how Wire works. This is how Wire handles key changes in reality: 

 - [Making your conversations secure](https://medium.com/@wireapp/making-your-conversations-secure-dab207ab77fd)

The second blog post describes an older version of Wire calls. Things have changed in the meantime, we explain it in more here:

 - [A major upgrade to calling](https://medium.com/@wireapp/a-major-upgrade-to-calling-9ac8780741a1)
 - [Call security – constant bit rate encoding and improving WebRTC](https://medium.com/@wireapp/call-security-constant-bit-rate-encoding-and-improving-webrtc-a85be6caa43a)

**Comment by EgbertW** [comment]
Thanks for the links. It seems the issues with calling have been addressed adequately. Regarding the conversations the concerns are also in relation to user experience.

The document you link to states:

```
The message is not automatically re-sent once Alice has added a new device. If Bob tries to send it again (because the “Sent” status tells him it hasn’t arrived), he will see the blocking take-over screen (shown below) to let him know Alice is using a new device.
```

'Sent' is not show by default - I have to actively tap the message to check if it's been delivered. A big exclamation mark could solve that, or any other visual indicator.

Another one is that the link you posted assumes that Bob and Alice will actually validate each others keys, and the test Tina Membe executed assumes users won't do this because it's too complicated (and she may be right here - see #95 ). In which case it looks like this.

https://cdn-images-1.medium.com/max/600/1*pgXP1X0hLHSjxBnceaTUog.png

I don't really have a way to test this as I've validated most of the keys so when something changes, I receive all these blocker pop ups. If the screenshot is correct, does that mean that as long as you don't validate any of the devices, Wire assumes that you have no interest in the keys at all?

**Comment by raphaelrobert** [comment]
If a message was not sent successfully, Wire will notify you. You will also clearly see an option to resend the message.

The warnings will only appear if all devices of a conversation have been verified.
This is what you would have to do if you want to be notified of a key change/a new device.

As I mentioned in #95, there will be improvements in the future to make things easier.

**Comment by EgbertW** [comment]
Ok, thanks for the clarification. This does indeed indicate that as long as you have taken no effort to validate your chat partners, it is assumed that you have no interest in knowing when their key has changed.

I do agree with the author that it would be preferable to inform the user of key changes. When the user hasn't taken the effort to verify keys it doesn't need to be a blocking pop up, but giving this information will not harm anyone, right?

**Comment by raphaelrobert** [comment]
This could be an option in the future.

Closing this now as all issues have been addressed.
