### ISSUE TITLE
Add Ring, Riot and Tox to your technical overview page

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire#105]
I especially liked reading through your technical oveview page: https://wire.com/en/privacy/
Could you add three of the strongest contenders for privacy to this list to increase transparency and comparability: Ring (https://ring.cx/), Riot (https://about.riot.im/) and Tox (https://tox.chat/). All three are comparable to Wire in terms of features in that they offer text, voice and video chats.

**Comment by teller** [comment]
@baimafeima The list of competitors there focuses on the ones with a larger market share. When we look at the volume of questions along the lines of "How does Wire compare with X" then these are the ones we get the most often.

Maintaining the comparison table isn't trivial either.

An idea would be to get in touch with the maintainer of https://www.securemessagingapps.com and suggest to add these there as an independent comparison site.
