### ISSUE TITLE
Prepare for traffic obfuscation

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire#107]
Currently - and this is the good news - Wire is working in China but it is a question of _when_ Wire traffic will be blocked. Are you currently implementing traffic obfuscation techniques to fend off DPI inspection?

**Comment by raphaelrobert** [comment]
Different countries block services in different ways.
This is something we will address in due time.

**Comment by cardassian-tailor** [comment]
Awesome. I hope you plan to be proactive, and not reactive. Planning ahead for such to occur and not waiting for it.

**Comment by kristin-wire** [comment]
Thanks for your request. Domain fronting is something we've discussed internally, but no concrete details to share at this time. 

Your request has been logged on our internal database for feature requests, and we'll close this ticket here now.
