### ISSUE TITLE
[Feature request] Make archive *completely* deletable

### ISSUE THREAD

**Issue by x2k13** [wireapp/wire#110]
Everytime a new device is added, all previously "deleted" content returns to the Archive tab on that device, clearly showing the leave-and-delete feature apparently not working as intended. Instead there are just dead, useless entries. This is happening on all platforms and all clients (web-app, iOS app, Android app, Desktop apps).

Please add a feature that makes it possible to completely remove/delete the archived content account-wide, including all 1:1 chats and group chats. As of now, apparently everything that was deleted is in fact archived, including empty 1:1 chats and empty group chats where all of the users left the chat already. 

IMHO it makes no sense to "archive" any content that a user clearly wants to be deleted, this should be considered as a seperate feature.

**Comment by kristin-wire** [comment]
Thanks for the feedback! Noted and shared!

Your request has been logged on our internal database for feature requests, and we'll close this ticket here now.
