### ISSUE TITLE
Wire on The Changelog!

### ISSUE THREAD

**Issue by jerodsanto** [wireapp/wire#111]
Howdy from [The Changelog](https://changelog.com/podcast)!

_(Never heard of The Changelog? We've been interviewing the hackers, leaders, and innovators of open source and software development since '09.)_

We'd love to have you on the show sometime soon. Who would be best person to join us to talk about Wire and all the cool stuff y'all are up to?

Please email editors@changelog.com to coordinate. 

Looking forward to it! 💚

**Comment by kristin-wire** [comment]
Sorry for the late reply here! Here's a link to the recording: https://changelog.com/podcast/279
