### ISSUE TITLE
Error in translation into Spanish

### ISSUE THREAD

**Issue by AyelGoth** [wireapp/wire#112]
In some parts of the application for linux it is mistranslated into Spanish. For example

In: YOU STARTED A CONVERSATION WITH = TÚ INICIASTE UNA CONVERSACIÓN CON
Or
YOU STARTED A CONVERSATION WITH = USTED INICIÓ UNA CONVERSACIÓN CON

YOU RENAMED THE CONVERSATION = TÚ RENOMBRASTE LA CONVERSACIÓN
Or
YOU RENAMED THE CONVERSATION = USTED RENOMBRÓ LA CONVERSACIÓN

CREATE TEAM = Crear Equipo

Remplace types emoticons by emojis = Reemplazar tipologías emoticonos por emojis

**Comment by lucilacaranza** [comment]
Hola Ayel,

Thanks for flagging. I see there are inconsistencies between tu, usted, and the verb forms.

This happens because we crowd-source all the translations.

If you would like, you could contribute towards improving the project. Please create an account on [Crowd In](https://crowdin.com) and request access to the project you are interested in: desktop / webapp.

We will grant you access and you can then start translating or proofreading.

Thanks,

**Comment by AyelGoth** [comment]
The translation error is found in a grammar error, between the article and the chosen verb tense. In some cases I have noticed that the verb is located after the noun. It is a common mistake to translate English into Spanish through electronic translators.

I long ago submitted the application to join the translation teams. It was rejected. Jejejeje.

**Comment by AyelGoth** [comment]
The first thing you should choose is what kind of Udeo you want to use, whether reverential voseo or American dialectical voseo. In Spanish there are three types of grammatical articles, (Vos, Tú and Usted)... Depending on the grammatical types, it is the verb in the phrase. In some cases, the verb goes before the noun, in other cases afterwards, depending on whether you are speaking in the first person or in the third person.

**Comment by lucilacaranza** [comment]
HI Ayel,

Perdon por la demora.

I am a native Spanish speaker myself. 

As I mentioned, the inconsistencies results from the fact that we crowd-source all translations, and there are several users translating strings in different ways. 

Would you mind re-applying for Crowd-in ? Let me know what your username is and I will accept your request. 

Gracias,

**Comment by kristin-wire** [comment]
Your request has been logged on our internal database for feature requests, and we'll close this ticket here now.
