### ISSUE TITLE
[Request] Windows Phone App

### ISSUE THREAD

**Issue by t-aus-m** [wireapp/wire#113]
I know that Microsoft has recently confirmed, that they are basically abandoning Windows Phone. But since the platform offers basically no good options ragarding messengers - even WhatsApp is buggy as hell - I am requesting you to port wire to Windows Phone.

**Comment by kristin-wire** [comment]
Thanks for the suggestion...not on our current roadmap.

Your request has been logged on our internal database for feature requests, and we'll close this ticket here now.
