### ISSUE TITLE
Feature: screen share, choose the monitor or the app you would like to share to reduce the video resolution

### ISSUE THREAD

**Issue by pdefert** [wireapp/wire#115]
First, the current feature seem work well on linux. i can share, and i can watch 
In multi monitor case, when we activate the screen share, the entire display area is used.
The functionality becomes unusable.
in my case,  i'm on ubuntu and i have 3 monitors and my contact see my 3 monitors on only one.

is it possible to add the choice of the monitor or only an application to reduce the resolution of the video?

Best regards

**Comment by kristin-wire** [comment]
Hi there, thanks for this request - it makes a lot of sense. Just to set expectations though, while this is a good request, it's lower down on the list.

Your request has been logged on our internal database for feature requests, and we'll close this ticket here now.
