### ISSUE TITLE
Message timestamps

### ISSUE THREAD

**Issue by gapop** [wireapp/wire#117]
Please add individual timestamps for each message, possibly only revealed on user action (as in the SMS app on iPhone). I find it's often important to know exactly when a message was sent.

**Comment by Namnodorel** [comment]
It's notable that the Desktop client already has this on mouse-over.

**Comment by gapop** [comment]
I noticed that the iOS app does that as well, although I only discovered the feature by accident. However, the Android app does not seem to have the feature at all.

**Comment by baimafeima** [comment]
I think timestamps should be more specifically to include the _date_ and not just the _day_.

**Comment by kristin-wire** [comment]
Try tapping on the message - the timestamp will appear below.
