### ISSUE TITLE
[Request] Changing Nicknames

### ISSUE THREAD

**Issue by AndrKolb** [wireapp/wire#118]
Since a lot of people choose nicknames which aren´t related to their real names, it would be great if wire hase the opportunity to change the names on my own contact list.

**Comment by trymeouteh** [comment]
This would be great way to organize your contacts so you know who is who. It would be even better if the renamed contacts are saved on the wire server encrypted for security and privacy.

**Comment by kristin-wire** [comment]
Seeing more of this request - keeping it in mind for the future.

We have logged this in our internal feature request database for tracking, and will close this request here.
