### ISSUE TITLE
Feature Request: sticker packs

### ISSUE THREAD

**Issue by miriamino** [wireapp/wire#119]
I know this is silly but one of the reasons so many people are still using telegram is the possibility to send stickers. Wire already has a lot of fancy features so why not let people have their stickers so they finally stop using telegram?

**Comment by yetzt** [comment]
I agree. Stickers are an important part in a broad group of peoples communication, even more so than gifs.

**Comment by neingeist** [comment]
yes, please

**Comment by oscalation** [comment]
I also agree. This would be a source of revenue also. Profit sharing with the sticker contributors would be cool.

**Comment by Geobert** [comment]
As silly as it sounds, this is the only thing that's keeping me (and some friends) using Telegram… messaging without the fun of stickers is so sad.

**Comment by stephno** [comment]
I agree with the comments above. Stickers are obviously not important for privacy or anything else, but for casual conversations, they surely do add “something”. That also keeps me from trying something else than Telegram. Could be great if this feature could be added in an upcoming update.

**Comment by kristin-wire** [comment]
Thanks all for your feedback, noted!

We have logged this in our internal feature request database for tracking, and will close this request here.
