### ISSUE TITLE
I'm on linux, with hidpi, and the font is atrocious, is there any way we could be allowed to change the font?

### ISSUE THREAD

**Issue by that1communist** [wireapp/wire#12]
Title pretty much says it all. 

There really should be a way to change the fonts built into the program, as well as a dark theme but thats a wholly different issue.

I changed the default fonts everywhere I could and found no solution, any help would be appreciated, thanks.

**Comment by that1communist** [comment]
http://imgur.com/E7LztKI
here you go.

**Comment by david-wire** [comment]
Thanks for the update, apologies for the delay in responding. This is not on our current roadmap, but we haven't ruled it out for the future.

Thank you for taking the time to send us your comments, and please feel free to contact us again if you have additional questions.

**Comment by wmengli** [comment]
Hi,
Sorry to tell you this is still not planned for this stage. We will close this for now and feel free to contact us for other questions.

Best wishes,
Wire Support Team
