### ISSUE TITLE
Android app keeps forgetting settings, email address and password

### ISSUE THREAD

**Issue by AxelBoldt** [wireapp/wire#120]
I'm using Wire 3.2.373 on rooted Android 7.1.2, LineageOS 14.1, Samsung Galaxy S2 i9100.

Upon starting the app, I enter my email address and password and get access to my conversations and contacts. Sending and receiving messages works fine. If I reboot the device (or stop the app with Settings/Apps/Wire/Force stop) and start the app, it asks me again for phone number resp. email address and password.

I have disabled the AdAware ad blocker, wiped the cache and Dalvik cache partitions, uninstalled and reinstalled the app, but the problem persists. No other apps on my device show any erratic behavior, however I see frequent "MTP host has stopped" messages (a known LineageOS bug: https://jira.lineageos.org/browse/BUGBASH-254). The system partition is formatted as ext4, data and cache as f2fs, the sdcard as vfat.

**Comment by kristin-wire** [comment]
Hi there, if this is still happening for you, please post directly in Android repository - a developer will get back to you.
