### ISSUE TITLE
[Feature Request] Voice Activity Detection

### ISSUE THREAD

**Issue by BVollmerhaus** [wireapp/wire#123]
While Wire's voice chat is great in terms of audio quality, it's still missing a basic feature that I think would benefit it greatly, which is Voice Activity Detection. Currently there's no way to set a minimum microphone level to transmit at, which means for example that others in my voice chat are forced to listen to me typing or clicking while I'm not talking. Introducing an option for VAD, as included in other voice communication programs such as TeamSpeak, would make talking to people with background noise less annoying.

![vad](https://user-images.githubusercontent.com/30414540/32949128-f48a82d4-cba1-11e7-910f-740bd1ed330a.png)

**Comment by jspittka** [comment]
Thanks for this message. We have this feature on the roadmap but it hasn't been prioritized yet. We like to avoid that users have to manually set the threshold. Getting all thresholds right requires extensive tuning and testing. Eventually we will get to it.

**Comment by BVollmerhaus** [comment]
I highly doubt that having a universal threshold would be possible, given how many different microphone configurations users could have. While a reasonable default threshold is fine, I think customizing it should certainly be an option in case the predefined one doesn't suit the user's setup. Not being able to change it could lead to a lot of frustration with the feature.

**Comment by kristin-wire** [comment]
Thanks for the feedback. We have logged this in our internal feature request database for tracking, and will close this request here.
