### ISSUE TITLE
Bug: not all URLs get detected correctly

### ISSUE THREAD

**Issue by Johann150** [wireapp/wire#125]
When using URLs with protocols that are not as common as http or even ftp, the URL gets detected as `https://`.

Example using the [dat](https://datproject.org/about) protocol which is used in the [beaker browser](https://beakerbrowser.com/):
![grafik](https://user-images.githubusercontent.com/20990607/32992630-2a998a1c-cd4d-11e7-9a4d-34a980680142.png)
When clicking on the link I get redirected to
```
https://9e7b96931632e9873180262336df392082bb5732de66c7285b371046fbdecb25/
```
which obviously makes no sense because that is not a registered host address.

**Comment by kristin-wire** [comment]
Mind reporting this directly in web repo?
