### ISSUE TITLE
URLs with '__' don't work properly

### ISSUE THREAD

**Issue by FSMaxB** [wireapp/wire#126]
I was sending this URL: https://github.com/xmikos/pwgen-passphrase/blob/6b419c2a26f347299215cc3ca0f247cbabb14246/pwgen_passphrase/__main__.py#L12-L14 via wire, but it interprets the `__main__` as bold text and stops the URL right before the `__`.

**Comment by kristin-wire** [comment]
From our side, it looks like it's fixed. Can you try again, and if it still happens, report on platform specific repo?
