### ISSUE TITLE
Topic-oriented messaging [aka E-Mail replacement]

### ISSUE THREAD

**Issue by fbruetting** [wireapp/wire#127]
Do you consider introducing topic-oriented messaging additionally to the current user-oriented chats? This way Wire may be able to replace the E-Mail system (and making SPAM pretty much impossible).

Requirements would be things like
- better interface for longer and marked-up texts,
- forwarding messages and answering to a partial group of people already in (B)CC,
- citations,
- editing previous text before forwarding/answering (annotations, deletions),
- handeling a lot more text practically,
- HTML markup,
- attachments,
- calendar management,
- etc.

Maybe there are bigger advantages if this could be done in some object-oriented way. So that for example, if you answer a message and add annotations inside the received text, these would be enclosed inside respective objects. These then could be easy referenced, or marked-up dependent to the client-side rendering engine, instead of how the sender marked it up by HTML. These "Re: Re: Re:" citations of the E-Mail are a big mess and object-oriented messages could improve that a lot.

**Comment by kristin-wire** [comment]
This is something we're seriously considering, but no details to share just yet. Current work around: create a group with yourself https://support.wire.com/hc/en-us/articles/360000293529-How-can-I-create-a-conversation-with-myself-

We have logged this in our internal feature request database for tracking, and will close this request here.
