### ISSUE TITLE
Feature: Groups in list of contacts or connections

### ISSUE THREAD

**Issue by AyelGoth** [wireapp/wire#129]
Groups do not appear in the list of connections or contacts.

When we are participating in a group conversation and delete it but do not mark it as leaving the group, the group disappears from the list of conversations. 

In the list of contacts or connections the group does not appear in the list, so we should look for the group again with the search engine.

The groups in which we are still participating should be on the contact list, so it would be easier to reopen the conversation. I would put it under the favorite contacts, and then the list of all the contacts.

**Comment by kristin-wire** [comment]
Nice idea, will pass it on to the team!

We have logged this in our internal feature request database for tracking, and will close this request here.
