### ISSUE TITLE
Insufficient information about telemetry collection and its usage for generated reports

### ISSUE THREAD

**Issue by Myllyla** [wireapp/wire#13]
Under **Edit:Preferences:Options** the user can chose to disable/enable "Usage and crash reports". The option is _enabled_ by default and it has _no_ information about what it exactly do.

Wire is known to take privacy seriously and the information sent is said to be anonymous, but the option can still be problematic with regards to European data protection and privacy authorities as the _consent_ is initially assumed, the user is expected to be already aware of the option if he wants to refuse consent, and any consent is likely to be invalid because the user don't know exactly _what_ telemetry is collected and _how_ it is processed.

"Usage and crash reports" should ideally be disabled by default and require opt-in. A reasonable option would be to ask the user for permission upon the first time launching Wire. This is how Mozilla Firefox solves it.

Anyhow. Any data collected will need to be specified and its purposes will in addition need to be specified, explicit and legitimate, and the data may not be further processed in a way incompatible with those purposes.

Please see the [Letter of the Chair of the Article 29 Working Party to Microsoft (15.02.17)](http://ec.europa.eu/newsroom/document.cfm?doc_id=42951), specially page 2 and their concern over the "basic" telemetry level in Windows 10.

![wire01](https://cloud.githubusercontent.com/assets/26203536/23589287/8140ecf6-01ca-11e7-9081-c03e703a3cc9.png)

**Comment by raphaelrobert** [comment]
Hi @Myllyla,

You can find more information about that in the Privacy Whitepaper: https://wire.com/en/privacy/#transparency
