### ISSUE TITLE
Feature: Access code

### ISSUE THREAD

**Issue by AyelGoth** [wireapp/wire#130]
Add the option to request an access code to unlock the use of the application on the different platforms.

Many users sometimes unlock their mobile phone and today there are different applications that can be used to clone and hack into messaging applications. This measure would serve to prevent this type of hacking.

**Comment by Madis0** [comment]
"Access code" as in OTP 2FA? Would be nice indeed.

**Comment by kristin-wire** [comment]
2FA is on our roadmap, but we don't have a timeline or further details to share just yet.

We have logged this in our internal feature request database for tracking, and will close this request here.
