### ISSUE TITLE
Feature request: Going the extra mile on the last seen, delivered, read etc.

### ISSUE THREAD

**Issue by fredmbarros** [wireapp/wire#131]
I'll be another user to ask for the possibility to check if a message I sent was read, but I think here Wire could go the extra mile in comparison to all other messaging services and let the user choose *individualy* which of our friends would be able to see the last time I've been online or if a message was read by me. Default could be as it is now, but then we'd go and change it for specific people.

The huge majority of people I know (myself included) disable read or last seen on WhatsApp because we don't want everybody to have that info, but surely we'd like to share this with *some* of our contacts.

Great app and service.

**Comment by t-aus-m** [comment]
I agree with this. Also this would reduce the "feature gap" between Wire and WhatsApp and the like.

**Comment by nibexo** [comment]
I understand that don't want that some group of people know when you were online. But I don't like this conception of hiding information that you read my message and ignored it.
BTW as I know currently in wire no feature which show that someone read message and when did it. For me it's big feature gap between Wire and WhatsApp/fb messenger

**Comment by kristin-wire** [comment]
For now, not on our roadmap, but will keep it in mind for the future.
