### ISSUE TITLE
feature request: chat with yourself only

### ISSUE THREAD

**Issue by lk16** [wireapp/wire#135]
In slack it is possible to have a chat with yourself: a channel where only you are in. 
This is useful for sending notes from one machine to another, or keeping a todo list or similar. 
As far as I know it's possible to emulate this by making a group with 2 dummy users and then kicking both of them. There has to be a better way.

Thanks for putting your time in this project, I like it a lot!

**Comment by kristin-wire** [comment]
We might have something for you soon...
