### ISSUE TITLE
Feature request: Graphical Emoji-picker and standardized Eomjis

### ISSUE THREAD

**Issue by t-aus-m** [wireapp/wire#137]
In my opinion, wire should feature a standardized Emojiset upon all clients (especially on desktop, where older Systems like Windows 7 or some Linux-Distros do not support all Emojis), preferably EmojiOne ore something similar. This way, all our favorite Emojis look the same, regardless whom we are sending them to. 

Also, and this is by far the more urgend request (at least imo) there should be a graphical Emoji-picker for Wire web and desktop. The thing (I don' want to call it picker) like it is now, is very very counterintuitive.

**Comment by kristin-wire** [comment]
Nice suggestion! Wire does not have our own emojis, but utilizes system emojis, which vary according to device and OS. Standardizing this with our own emojis isn't on the immediate roadmap.
