### ISSUE TITLE
Hide Giphy search term after submitted

### ISSUE THREAD

**Issue by PortableStick** [wireapp/wire#139]
My friends and I really enjoy the ability to search for and use gifs within the apps, but having "<search term> · via giphy.com" sent along with the image can really spoil some jokes.  I'm not sure what the purpose is to having it at all and think it should just be removed from the app entirely, but at least having an option to disable it would be great.

**Comment by cardassian-tailor** [comment]
Yeah I agree, it gets in the way and sometimes takes away from the context of conversation. I think the best option would be probably to leave it, but hide it behind an info icon next to the giffy image. Or just give the search terms as additional info if the user clicks on the giffy image to open it directly in the app.

**Comment by jschaul** [comment]
This is probably due to Section 5 A of [Giphy's Terms and Conditions](https://giphy.com/terms).

**Comment by cardassian-tailor** [comment]
yep @jschaul your right. Well then that settles that I guess.

**Comment by kristin-wire** [comment]
Thanks all for your feedback. Your request has been logged on our internal database for feature requests, and we'll close this ticket here now.
