### ISSUE TITLE
GUI improvement for missed calls

### ISSUE THREAD

**Issue by cardassian-tailor** [wireapp/wire#141]
This is a feature suggestion that would really just require changes to the GUI. 

When you preform a call, and the other end does not answer you are presented with a screen showing that the caller didnt answer. On that page should be an icon to leave a voice message (like a voice mail). That ability is already there if you make a few clicks but I think putting it there will make the interaction easier for users and increase that features usage. 

Then, as its usage increases, I suspect more users would be interested in a dedicated location for voicemail messages on the home screen of the application.

**Comment by kristin-wire** [comment]
Interesting suggestion! For now the audio message feature already on Wire could serve as a work around for you.
