### ISSUE TITLE
[Security] Group Messaging in Wire

### ISSUE THREAD

**Issue by nenadandric** [wireapp/wire#144]
I have found this information of the new paper regarding group messaging in some IM services
https://blog.cryptographyengineering.com/2018/01/10/attack-of-the-week-group-messaging-in-whatsapp-and-signal/
Could you please let us know what is the status of group messaging in Wire, and if similar problems exist?

Thank you

Paper:
https://eprint.iacr.org/2017/713.pdf

**Comment by lucilacaranza** [comment]
Hello,

Thanks for flagging!

Group management in Wire works somewhat differently, so the research is not directly applicable. We are talking to the researchers and hope that Wire gets included in the next round of this research.

Best,Wire Support - Lucy
