### ISSUE TITLE
The ability to actually delete a connection

### ISSUE THREAD

**Issue by cardassian-tailor** [wireapp/wire#145]
Please, please, please work on creating a way to actually disconnect and delete a contact. Yes, we are familiar with  the ability to ignore a user and archive them. 

I would **love** to hear some short and simple details as to how the current functionality actual works. From my understanding wire use rotating public keys for users/groups. So when you connect the users exchange public keys. So when user Alice sends bob a message, Alice encrypts the message with bobs public key, and then bob can decrypt it with his private key. Great. Now, bob ends his relationship with Alice and 'forgets' and 'archives' the connection. 

Alice still has bobs public key. Does bob's account now go through a phase where it generates a new public and private key, distributes it to all connections except Alice? It keeps the old keypair to keep all prior conversations but doesnt use them for new messages? A revocation of sorts. 

Does bobs wire account just notate to itself to not decrypt messages from Alice? Does this occur at the device or on the server?

**Comment by kristin-wire** [comment]
I hear you, would love this feature as well, noted and thanks!

**Comment by Aikatsui** [comment]
https://github.com/wireapp/wire-webapp/issues/11198 https://github.com/wireapp/wire/issues/206
