### ISSUE TITLE
ping does not trigger a chime

### ISSUE THREAD

**Issue by chrishying** [wireapp/wire#147]
Ping does not produce an acoustic signal on the recepient's app.
it does produce an acoustic signal on the sender's app, though. 
Tested both directions.

observed on Android wireapp 3.4.382.
from Android app to Android app.

**Comment by someoneEsle** [comment]
Hey @chrishying , sorry for the late reply. We track android bugs on the android repository (https://github.com/wireapp/wire-android/issues) so next time you can open the bug report there and hopefully get a faster reply :)
That being said, is this still happening to you? Could you update to the latest version? Is the app in foreground or in the background when you are testing this?
Thanks!

**Comment by chrishying** [comment]
Hi @someoneEsle, 

thank you for your reply.

The issue is still observable with Wire 3.6.391

If it is helpful I can close and re-open this issue in the queue dedicated to Android.
your advice is appreciated :)

**Comment by someoneEsle** [comment]
Yes please :) That way you will see a form when creating the issue that helps us gather all the information we need to debug. Thanks!
