### ISSUE TITLE
Contact Groups

### ISSUE THREAD

**Issue by mk768780** [wireapp/wire#15]
I have a lot of contacts. It would be great if you could group them into areas or groups on your phone. Like personal and work area and tag contacts or groups into areas. 

Thanks.

**Comment by david-wire** [comment]
Thanks for the feedback. We do take this into consideration.

We're pleased to say that we have heard from many of our users about specific features that they would like to have. Whilst we don't comment on exact dates for feature releases and enhancements, as soon as we have new developments, we will communicate them via our website and our blog.

We are taking users' desired features very much into account in our planning, and we aim to get new features out as quickly as we can.

**Comment by wmengli** [comment]
Hi, we will close this for now and feel free to contact us for other questions.

Best wishes,
Wire Support Team
