### ISSUE TITLE
image delivery and user notification usability improvement 

### ISSUE THREAD

**Issue by cardassian-tailor** [wireapp/wire#153]
I have a small suggestion for a usability improvement. 

Currently the user is notified as soon as a message is delivered, including when a message contains an image (possibly also with audio but I haven't tested it)

The problem is - often the image needs to be transferred and you see the default blank square until the transfer completes. However, you've already received the notification, picked up your phone, unlocked it, and looked at the message feed only to be disappointed that the content isn't ready for you to view. 

Suggestion: Do not notify the receiving user (via vibration, audio notification, icon flashing, etc) of an new message that contains an image (possibly also audio) until the entire transfer has completed.

**Comment by kristin-wire** [comment]
Nice idea. Would require some heavier lifting on our side, but something to consider for down the road.
