### ISSUE TITLE
Send images with reduced resolution

### ISSUE THREAD

**Issue by jullit31** [wireapp/wire#155]
Many modern phones have 16+ Mpix cameras, which is great in some cases. However often you just want to quickly share a picture with someone who will only view it on their phone or computer monitor. In such cases the full camera resolution is rather excessive, just wasting time and data. So it would be great to have the option to send images with reduced resolution, maybe something like this:
![mockup](https://user-images.githubusercontent.com/19243986/35303161-4911c0be-0091-11e8-8d46-87bdef8aa7d2.png)
The button should then give you options for lower resolutions, for example 720p, 1080p and 4K.

**Comment by kristin-wire** [comment]
Thanks for the feedback! Noted and shared!
