### ISSUE TITLE
App: Annoying Usability issue-please let the user go back to the main app-screen (or any other screen on the phone) while calling!

### ISSUE THREAD

**Issue by zumbatan** [wireapp/wire#156]
HI Wire!
Nice app! but really, please eliminate this highly disturbing usability flaw:
a) Description:
open Wire, click on one contact, and call him. while the call continues, click on the "go back" button on your phone (or a currently non-existent "go back" button within the top left corner in Wire's call screen) to go back to the chat screen. then leave the wire app, and open any other screen on your phone, for example the calendar.

b) Expected results:
After you placed the call, the usual call screen of Wire appears with options to end/mute/put on speaker, etc. - After hitting the "go back" button of your phone (or a currently non-existent "go back" button within the top left corner in Wire's call screen) , the screen changes and you see the chat screen of the respective contact. - You are able to leave the Wire screen and open the calendar app of your phone, or any other view.

c) Missing features:

    A "go back" button within the top left corner in Wire's screen while a call is placed
    The ability to be able to leave the Wire app (surely it runs in the background) while at the same time staying on your call (a status-symbol indicating the ongoing Wire call can be displayed within androids/ios usual "notification" bar at the top of the phone-this way users can switch again easily back to the Wire call screen)

PLease act on this highly annoying usability issue, Wire Devs! During calls there are so many information exchanged, you wanna be able to go back to the actual chat screen to look for such information , instead of being forced to end calls , only to lookup for something, and again call back, and again forget a detail, and again hang up, and again look up, and again call back... you get the annoyance factor, i hope?! I bet every 2nd person is annoyed by that.

Please act swiftly i am not sure how much of development effort this change will be? Please enlighten us about your opinion on this and when you might take it on?

Thank youuu:)

PS: And something is wrong with your TIMEstamps within chats... they are not always shown for EACH separate text, and almost NEVER shown for separate phone calls.
@someoneEsle   @red-avtovo

**Comment by jullit31** [comment]
Hey zumbatan,
you might also want to take a look at wireapp/wire-ios#263 or wireapp/wire-android#750 or wireapp/wire-android#829 and add your voice there.

Some news from the team about this would be nice though.

**Comment by kristin-wire** [comment]
Hi there, you're absolutely right, and a great feature request! It's something we are discussing internally, but no concrete news to share just yet.
