### ISSUE TITLE
Knowing that your old sent messages will never be delivered

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire#159]
Wire server store messages for 28 days. It means that if your recipient doesn't connect for more than 28 days, old messages will never be delivered.

Message that are more than 28 days old must be marked as such and wire sould give to the sender:
- a visual status for this message (they are unsendable)
- a mean to resend them (and reload the 28 days grace period)

**Comment by IpsmLorem** [comment]
Another possible case : your recipient didn't connect for more than 28 days. Then, he changed his device and removed the old one. 
The old messages cannot be decrypted by the new device (new key pair) but the sender doesn't know that his previous sendings will never be delivered.

**Comment by kristin-wire** [comment]
Hi there, thanks for this request - it makes a lot of sense. Just to set expectations though, while this is a good request, it's lower down on the list.

**Comment by IpsmLorem** [comment]
It's lower down, but why closing it ?

**Comment by kristin-wire** [comment]
Ah, good question!  We log all these request via support  - so essentially to funnel all requests to one place - easier to search and quantify then.
