### ISSUE TITLE
Bot developer registration

### ISSUE THREAD

**Issue by ehmry** [wireapp/wire#16]
The bot developer registration is confusing and possibly broken. I registered an email address with the donbot and after verifying my email from a browser I get a split second message that I wasn't able to read. No response after a week. I try a different email address, get an approval email, and the donbot says "Authentication failed" for every command but "register".

I have better things to do then piddle around with registration, but this doesn't make me feel like its worth the time making a bot at the client API.

**Comment by dkovacevic** [comment]
Can I get more info on this, please? Wire @username that was used to talk to DevBot and both email addresses used to register, please.

Thanks!

**Comment by ehmry** [comment]
Username is ``@emery``, first email was wirebotjunk@spam.works (a real address) and second was emery@vfemail.net.

**Comment by david-wire** [comment]
Thanks. Could you either verify the very last email you used *or* try to register with a brand new one (not any of the ones you mentioned above)?

**Comment by ehmry** [comment]
Using the very last mail returns "This email address was already used to register", so I used a new one.

**Comment by dkovacevic** [comment]
Thanks! You should be able to create bots now. Let us know if you still experience issues.

**Comment by ehmry** [comment]
Yep, it works, thank you for your help.
