### ISSUE TITLE
Feature request: Wipe conversations and better customization

### ISSUE THREAD

**Issue by click2respawn** [wireapp/wire#161]
I would like to disable gifs, file transfers and calls completely but looks like it's not possible at the moment. On top of this there is no way to wipe chats from both sides. I am still using telegram because of their timed messages are really good, I just don't wanna leave any information behind. Right now I can set timer for things I write and to be honest it is not enough, it should work  for everyone in that chat.

**Comment by kristin-wire** [comment]
Thanks for your feedback. 
Your first request is noted, and something we'll keep in mind for the future.
Regarding your second request, this is not on our roadmap, but I'll share your feedback with the team!
