### ISSUE TITLE
Close button not working

### ISSUE THREAD

**Issue by mik1osh** [wireapp/wire#163]
Current behavior: when I click close button [x] (on windows top) the application does not close.
Expected behavior: when I click the close button [x] (from the top of the window) the application closes.

Optional: add the ability to change the reaction of the application when you click the "Close" button.

**Comment by kristin-wire** [comment]
Hi there, from our side, it looks like normal behavior...the app is minimized. To close Wire, you can go to the Task Viewer in the bottom right of your screen. (See screenshot)

![76462e99-ccbd-4a7b-b16e-3cd57c9bc0e9](https://user-images.githubusercontent.com/7021978/36261858-04181eea-1266-11e8-8a9f-ad3cd2b745e5.png)

**Comment by mik1osh** [comment]
this is absolutely not normal behavior, "close application" button should close the app!
![2018 02 15-18 05 18](https://user-images.githubusercontent.com/21007685/36263595-95416042-127b-11e8-8aac-8cf91206334e.png)

**Comment by mik1osh** [comment]
[re-open bug request]

**Comment by mik1osh** [comment]
[re-open bug request]

**Comment by mik1osh** [comment]
[re-open bug request]

**Comment by mik1osh** [comment]
[re-open bug request]

**Comment by mik1osh** [comment]
[last re-open bug request]
