### ISSUE TITLE
Feature Request: Recording Video/Audio Calls

### ISSUE THREAD

**Issue by trymeouteh** [wireapp/wire#164]
A cool feature to see if the ability to record the video and audio call and after your stop recording or end the call it will save the file as a video/audio file of your desire. (Common audio/video files and maybe high quality video/audio files if Wire uses high quality audio/video) But a privacy minded way to implement this can be done with the following...

1: When a users starts recording a call the other users in the call will be notified that this call is being recorded.

2: When a user starts recording a call the other user in the call will get a notification asking permission to record the call. If approved the call will be recorded.

3: The same as 2 with the additional feature of having a blacklist/whitelist on users who you will allow to record your calls.

**Comment by kristin-wire** [comment]
Thanks for your feedback. This isn't on our immediate roadmap, but here's a bit more information from the community about ways to do this: https://medium.com/@wireapp/recording-podcasts-via-wire-on-macos-7b83b4669bb1
