### ISSUE TITLE
sporadic, non-planed release schedule is a security risk

### ISSUE THREAD

**Issue by cardassian-tailor** [wireapp/wire#166]
Wire needs a release schedule. This doesnt include a promise for new features at set intervals or that your internal roadmap needs to be made public, it merely means that users should have an idea as to when an update should occur. 

Say, once every two weeks I should expect the applications to update ... even if its just updating the version number. 

Also, the release notes are undoubtedly geared towards normal, non technical users. It would be beneficial if you would list at least the updated hashes for the applications within the release notes (i know its on the download page)

**Comment by kristin-wire** [comment]
Thanks for the idea! Software development can be a winding road however - when bug crop up, testing, approvals from QA and app stores- these things can affect projected timelines. Many of the features we're working on are larger, resource intensive projects that take longer that 2 weeks to complete. Nevertheless, we work hard to get new releases out regularly.
