### ISSUE TITLE
Feature Request: @username profile URLs

### ISSUE THREAD

**Issue by rummik** [wireapp/wire#167]
It would be pretty handy to be able to link to my account from other services with a URL something like `https://app.wire.com/@rummik`, `https://app.wire.com/user/rummik`, or `https://app.wire.com/user/<id>`

At first glance, this looked somewhat like it was covered by #88, but that seems to be more for a timed invite link, rather than a profile link

**Comment by cardassian-tailor** [comment]
This would place wire into a weird position of being the custodian of that data which would be presumably unencrypted if it’s open to non connected contacts.

**Comment by rummik** [comment]
Given this information is searchable when finding contacts, I assume it is already stored unencrypted

**Comment by cardassian-tailor** [comment]
Ah. I though you meant allowing users to add more details more images. Sort of like a wall.

**Comment by rummik** [comment]
Oh, no, I'd just like to link to existing information so folks don't have to search for it

**Comment by kristin-wire** [comment]
Possibly something for the future, thanks for the feedback.
We have logged this in our internal feature request database for tracking, and will close this request here.

**Comment by kesenwang** [comment]
I really wish this would be implemented as well, it’s kind of awkward actually cause really can’t even link to like @username in Twitter because it will register as another Twitter profile. Wish this would have been implemented.
