### ISSUE TITLE
wire, resources hungry 

### ISSUE THREAD

**Issue by letkan** [wireapp/wire#168]
Hi 👋, 

thanks for reaching out!

If you are reporting a bug or have an issue for a specific platform or project, please open the issue in the corresponding repository:

- [Android](https://github.com/wireapp/wire-android)

Of all the communication apps I have on my phone wire uses the most resources (read,  battery): Whatsapp including chat and phone daily several hours uses like 2-3%, Wire just standing by, 14%. That's on LOS 14.1 on a Xiaomi Mi4c device. I generally disable battery optimization for this kind of apps.

**Comment by kristin-wire** [comment]
Hello, please direct your feedback to the specific platform -eg Android.
