### ISSUE TITLE
Wire connected me with an unknown account without my approval

### ISSUE THREAD

**Issue by mandreyel** [wireapp/wire#169]
Today Wire notified me that I have been connected to an unknown account. However, I have not approved any contact request, nor am I aware of anyone seeking to connect with me via Wire at present time.

It could be that someone randomly selected the name and found me, but this doesn't explain why the request was automatically approved. Could this be a bug in that this contact request was meant for another account but was erroneusly routed to me?

I suspect this is not a lot to go on, but unfortunately I was in a rush when I received the notification and forgot to extract logs. How can I provide relevant information?

**Comment by kristin-wire** [comment]
Auto-connections are Wire contacts whose phone number appears in your address book, or vice versa. To reject an auto-connection, simply block the user in your conversation list. 

Your comment has been logged on our internal database for feature requests, and we'll close this ticket here now.
