### ISSUE TITLE
[Feature Request] Enable access to conversation history anywhere by implementing an auth scheme similar to ProtonMail

### ISSUE THREAD

**Issue by nikolowry** [wireapp/wire#17]
I've failed in my attempts to limit my use of Wire to the web app. Unfortunately I've lost too many messages over the "no conversation history on new devices" feature due to the fact I proactively clear my cookies, cache and storage on atleast a weekly basis.

Instead of using devices to fingerprint users - which is why I'm not recommending the typical two-factor auth paradigm which can also be gamed with social engineering - I'd like to instead suggest using a model similar to the one ProtonMail utilizes:

- On new sign-up up a user provides two passwords, a "Login" and "Mailbox" password.
- On current-user login you have to provide both passwords to gain access to your Mailbox.

The "no conversation history on new devices" feature is just security theatre. It's a fallacy to reason that tracking my device is ensuring any privacy, per the fact I just gave up privacy the moment it was fingerprinted by your service.  

And what's to say that a user forgets to lock their device which results in a nefarious actor getting physical control of it - all that security just got defeated by human error. 

> *Real world example*
>
> When I develop Android apps I might enable "Don't lock screen while phone is charging" and occasionally leave the phone unattended at my work desk.  While I'm usually pretty conscious of locking, I'm not 100%.  
> 

Following that example, if you had the double-password auth implementation another feature could be enabled that requires the second password on Activity start/resume. 

On a positive note, thank you for being the only encrypted app that doesn't require a mobile number and also one of the few developing in the open. Don't let my "armchair quarterback/backseat driver" commemts discourage you!

**Comment by david-wire** [comment]
Thanks for the detailed feedback.
We do not store any history of conversations on our servers, so this comparison with a 2 step login process to access a mailbox does not apply.
Do you want to give us a bit more details on what you would expect going forward?

**Comment by nikolowry** [comment]
@david-wire thanks for the quick feedback did not know that no messages are stored on anywhere external. 

I guess I should look at the full codebase before making assumptions and suggestions.
