### ISSUE TITLE
Feature request: mentions

### ISSUE THREAD

**Issue by something3** [wireapp/wire#170]
It should be possible to mention people by their name.

In Telegram this is done with 'at', like @username

Then the mentioned user gets a clickable button that scrolls to the mention (useful when out of the loop for a time and just need to read something in the middle of hundreds of posts).

Currently there are only pings, which are a bit like that, but don't work as a way of addressing a specific person.

**Comment by kristin-wire** [comment]
Nice suggestion! This is something we're looking into!

Your request has been logged on our internal database for feature requests, and we'll close this ticket here now.

**Comment by cardassian-tailor** [comment]
https://github.com/wireapp/wire/issues/221  duplicate issue/feature request. #221

**Comment by cardassian-tailor** [comment]
https://github.com/wireapp/wire-ios/issues/781
