### ISSUE TITLE
Allow searching the user list

### ISSUE THREAD

**Issue by dwt** [wireapp/wire#171]
This issue seems to affect all UIs, thus I am reporting it here.

Problem:
My User-List has gotten so large, that I occasionally completely get lost finding the user I actually want to chat with. Having the user-list sorted by LRU does both help and hinder in this regard, as it does mean that my recent contacts are at the top, but also means that not so recent contacts can be anywhere, and I have to manually search through the whole list to find them.

Proposed solutions:
1. Magically always show me the person I wanted to chat to
2. Allow some way to search in the user list

I would prefer 1., but I'd settle with 2....

**Comment by ehodzic** [comment]
You can already search the user list. To the left of the settings button there is the "Start Conversation" button. It looks like this:
![screen1](https://i.imgur.com/97MW5S2.png)

Once you click that, you can search for people in your connections list.

**Comment by dwt** [comment]
Hm, I never searched for that feature there. Thanks for mentioning it.

I would like to note however that this may be bad usability, as most other chat clients I know provide a search field at the top of the user-list (on iOS maybe scrolled out the top by default).

Something like this would (IMO) greatly help in making that feature discoverable.

**Comment by kristin-wire** [comment]
Thanks for the feedback! Noted and shared!

Your request has been logged on our internal database for feature requests, and we'll close this ticket here now.
