### ISSUE TITLE
Can play but not save/download received video clips in desktop app on linux (Manjaro and Mint)..

### ISSUE THREAD

**Issue by chimanic** [wireapp/wire#172]
Hi 👋, 

thanks for reaching out!

If you are reporting a bug or have an issue for a specific platform or project, please open the issue in the corresponding repository:

- [iOS](https://github.com/wireapp/wire-ios)
- [Android](https://github.com/wireapp/wire-android)
- [Web App](https://github.com/wireapp/wire-webapp)
- [Server](https://github.com/wireapp/wire-server)

**Comment by kristin-wire** [comment]
Yes, indeed - please report this to Wire Desktop repo.
