### ISSUE TITLE
Feature Request: invite users to a group via link

### ISSUE THREAD

**Issue by colttt** [wireapp/wire#173]
Hi,
it would be really nice if we can create a group and send a link to invite users (like Telegram do). That is very usefull if you have a Mailinglist and want to invite all users if they want, so I don't need they PhoneNumber/Mailaddress/Nick or so. They just klick on the link and the wire client open to join this group.

Best regards

**Comment by kristin-wire** [comment]
This is coming very soon, hang tight!
