### ISSUE TITLE
Add Backup and Restore

### ISSUE THREAD

**Issue by dns2utf8** [wireapp/wire#174]
Hi 👋, 

I need to migrate to a new phone soon, android -> unknow, and I would like to keep my history.
What I would need:
- encrypted export (eg. a 7zip file) containing either the key and contact list for a small backup or everything for a complete one
- optional: either
    - block old device from using the same key or
    - migrate everything to a new key on the new device (maybe allow the old key to continue to be used)

Cheers,
Stefan

**Comment by marove2000** [comment]
+1

I would appreciate also a incremental backup. My experiences with threema (Backup-Size up to 2GB) are not very good with encrypted .zip-files.

**Comment by kristin-wire** [comment]
Thanks! 

For first request - history backup is something we are working on now, but I don't have further details to share publicly now. For the second request -nice idea. Would require some heavier lifting on our side, but something to consider for down the road.

Your request has been logged on our internal database for feature requests, and we'll close this ticket here now.
