### ISSUE TITLE
Rename devices [Feature Request]

### ISSUE THREAD

**Issue by wizzard0** [wireapp/wire#175]
When using Wire in the browser, it's very hard to tell one computer from another if you need to remove one.

**Comment by kristin-wire** [comment]
Thanks for your feedback. We're hearing more of this from our users, and keeping it in mind for the future.
Your request has been logged on our internal database for feature requests, and we'll close this ticket here now.

**Comment by Mikaela** [comment]
Are there any news about this? There is [Staying anonymous on Wire](https://medium.com/@wireapp/staying-anonymous-on-wire-22faa13aba4d) from Apr 26, 2017 (not long after https://github.com/wireapp/wire-webapp/issues/313#issuecomment-295296200 where I was going to comment originally) on your Medium, but it doesn't address this issue.

I think devices not being renameable allows using Wire for identity correlation if there is a suspect on some users being the same.

![Screenshot from 2019-05-27 19-00-27](https://user-images.githubusercontent.com/831184/58430421-df39c400-8098-11e9-99c8-d0f4315b9ec5.png)

How common for example is my device list amongst Wire userbase (adding Wire Linux)?
