### ISSUE TITLE
deleting an account doesnt seem to fully delete an account

### ISSUE THREAD

**Issue by cardassian-tailor** [wireapp/wire#176]
This effects all versions of wire

If you delete your account, then create a new account and search for your old account (even after waiting 30 days) your old account is still listed and the profile image is still shown. 

Immediate questions that come to mind is ... what other data still exists? 
Is the account actually deleted? 

Is this intended and expected behavior? Does delete not equal delete?

**Comment by cardassian-tailor** [comment]
probably related : https://github.com/wireapp/wire/issues/55  

Ive commented there as well.

**Comment by someoneEsle** [comment]
Hey, thanks for reporting. Are you sure you successfully deleted your account? It sounds like it was not deleted. Can you share the @username of this account publicly? If not you can write an email to support@wire.com and link to this github issue.

**Comment by cardassian-tailor** [comment]
@someoneEsle 

Yes, I can. I will email support now and reference this issue.

**Comment by kristin-wire** [comment]
Glad to hear it's resolved. Let us know at support if you have any additional questions.
