### ISSUE TITLE
Feature request: Encrypting password reset

### ISSUE THREAD

**Issue by Eriton33** [wireapp/wire#177]
Wire currently allows for password resets via phone number or mail address.
Both are not really secure methods, especially when sending reset keys via mobile.

It would be nice to have an option to set a pgp key, which will be used to encrypt the password reset link/string/code.

Using pgp would also be a relatively simple method that can easily be implemented.

Note: For changing the suggested option, e.g. removeing it or changing the key ID another pgp encrypted challenge would be needed to make this option effective. 
Losing the pgp key would mean to permanently lose access to the associated wire account.

**Comment by cardassian-tailor** [comment]
I would say the easiest (and maybe better approach) would be to use the tested and trusted u2f FIDO option. There are now open source libraries for such. This is a much better path.

**Comment by kristin-wire** [comment]
Noted, and shared, with the team, thanks!
Your request has been logged on our internal database for feature requests, and we'll close this ticket here now.
