### ISSUE TITLE
no phone

### ISSUE THREAD

**Issue by AvoidMastodonBlue** [wireapp/wire#178]
how do i register an account without a phone?

i recall a webclient registration option

**Comment by DestinFaroda** [comment]
You don't need a phone for Wire. Simply download the software for your operating system (or use the WebApp) and create an account with an email address of your choice.

**Comment by kristin-wire** [comment]
Exactly! This might be of  help too: https://support.wire.com/hc/en-us/articles/360000208485-How-can-I-register-with-an-email-
