### ISSUE TITLE
full screen button

### ISSUE THREAD

**Issue by oscardssmith** [wireapp/wire#179]
Hi peoples,
I just started using Wire and really like it, but the one thing I've found that would really be great to add would be a way to make a video call go to full screen rather than by manually full screening the window.
I'm not entirely sure if this should be filed under the web-app or here so I've guessed.
Thanks

**Comment by kristin-wire** [comment]
Hi there, yes if you could file under web app repo, that would be great.

Cheers!

**Comment by oscardssmith** [comment]
ok. done
