### ISSUE TITLE
Ability to @ mention a user in a group chat or mention everyone

### ISSUE THREAD

**Issue by WildYorkies** [wireapp/wire#181]
https://github.com/wireapp/wire-ios/issues/781

Since the server cannot read messages, this feature has to be added to clients. 

Groups of more than 3 people are typically going to be muted by default so a users phone doesn't explode with notifications. In this very common scenario, we need the ability to override the mute by @ mentioning the username of the person.

Ideally, we should also get the ability to override _all_ mutes by mentioning the group with `@all` or something similar.

Thank you and keep the updates coming :D

**Comment by kristin-wire** [comment]
This is something we're looking into for the future.
