### ISSUE TITLE
More than one person with the same name in a chat

### ISSUE THREAD

**Issue by forteller** [wireapp/wire#182]
I think there should be a better way to handle this than currently. In the chat window you might look at the picture to see who it is who said what, but in notifications, when searching, etc, the fact that more than one person is just given the same name is a bit user unfriendly. I would suggest that all the people with the same first name should be referred to as both first and last name in a group conversation. Or, if it's difficult to only do this with people with the same first name, that all people in group conversations should be referred to with both names.

**Comment by kristin-wire** [comment]
Customizing a contact is a feature request we're seeing more of. It's not on our immediate roadmap, but also something we haven't ruled out for the future.

**Comment by forteller** [comment]
I'm not asking for manually customizing contacts, though. I'm asking for both first and last names to be shown automatically when there are more than one contact with the same name in a group chat. The intuitive thing is that this happens automatically, not that you have to know that you can, and know how to, customize how the contact is shown, and then have to do it yourself.
