### ISSUE TITLE
Feature request: Modern UI

### ISSUE THREAD

**Issue by marlid91** [wireapp/wire#184]
I really like WIre, but I hate that GUI is so bloated and takes up half my screen. Will we ever see better UI that puts the conversation in focus and is resizable so that it's only a fraction of the size that it is now? 

Here are a few example of how bloated Wire is compared to iMessage:

<img width="1523" alt="wire-2" src="https://user-images.githubusercontent.com/32309127/38767398-da46d59c-3fcf-11e8-9111-0939fdc2302e.png">

You can fit the entire iMessage UI into Wire's chat box:

<img width="902" alt="wire" src="https://user-images.githubusercontent.com/32309127/38767405-e9458bc4-3fcf-11e8-8515-ef1792d31b30.png">

The situation is the same with other chat apps like Caprine (wrapper for Facebook messenger) and even Skype. Hopefully Wire will rectify this situation soon because the UI is annoying as it is.

**Comment by kristin-wire** [comment]
Thanks for the feedback. The request to resize windows is one we're seeing more of, and are keeping mind for the future.

Your request has been logged on our internal database for feature requests, and we'll close this ticket here now.
