### ISSUE TITLE
Feature Request: Dark background for Wire Desktop App

### ISSUE THREAD

**Issue by devagent42** [wireapp/wire#185]
Hello,

I would like to request a feature. I would like to request dark background for the Wire Desktop App.

Thanks,
devagent42

**Comment by cardassian-tailor** [comment]
Yes please. The white background is really hard on the eyes.

**Comment by kristin-wire** [comment]
Request noted, thanks! Your request has been logged on our internal database for feature requests, and we'll close this ticket here now.
