### ISSUE TITLE
No confirmation email in the Developer (Provider) account registration process.

### ISSUE THREAD

**Issue by weareua** [wireapp/wire#187]
I try to get started with bot creation for Wire, but can't create Developer account (aka provider). I tried two emails for registration purpose (protonmail and gmail), but have got no confirmation email.

I used this script to create provider/developer account. Please refer the screenshot
[https://github.com/wireapp/echo-bot/blob/master/myprovider.sh](https://github.com/wireapp/echo-bot/blob/master/myprovider.sh)

BTW maybe someone can tell how I can reach out the bot for creating bots? All links that I found redirects me to my last conversation.

I use archlinux if it matters.
![screenshot_20180425_130820](https://user-images.githubusercontent.com/12089247/39245602-e6cd4546-489c-11e8-9969-384986b77257.png)

**Comment by dkovacevic** [comment]
Most likely you provided homepage without schema (https). Try passing something like: https://www.myhomepage.com
I have added some debug info in `myprivider.sh` that can help too:
https://github.com/wireapp/echo-bot/commit/485159a8916ed3953fe5cf6cfa47c3e774b9cf04

Keep in mind Bots are enabled _only_ for teams. The same applies for Don (Dev bot)

**Comment by weareua** [comment]
Thanks, @dkovacevic! Now I did receive the email after filling "Provider homepage" field. 

Does it mean that people, who use personal (free) wire edition can't use bots?

**Comment by dkovacevic** [comment]
The answer to your question is: Yes and No.
On one hand business wants to enable and advertize bots ( aka Integrations) only for paid version of Wire (Wire for teams), Backend does not enforce (for now) this limitation.

In theory you could use `curl` to add your service (bot) into a conversation...

In case you have your service enabled and up and running you could use this shell 
https://github.com/wireapp/echo-bot/blob/develop/add.sh

Login in with your Wire credentials ( user creds, not the provider's one), pass your serviceId/providerId...

I know, it's not perfect but hey...
