### ISSUE TITLE
Progressive message deletion with time

### ISSUE THREAD

**Issue by natolh** [wireapp/wire#190]
With time we accumulate a lot of messages / documents in Wire conversations. Keeping all this messages is not necessary for all users and it take space on devices. There is always the possibility to erase the whole conversation, but in that case we loose most recent messages.
It would be usefull to have a feature that automatically delete old messages. One like the Apple iOS message app.

If implemented, should be an opt-in feature, and it would be neat to allow a per-conversation activation. It would be better to offer the possibility for fine grain expiration period, but a predefined set of options is great to. For reference, Apple message, offer: 30 days and 1 year periods.

**Comment by cardassian-tailor** [comment]
I agree. 

It should also give you the option to delete messages on your device and sent.

**Comment by kristin-wire** [comment]
Thanks for the suggestion. 
Your request has been logged on our internal database for feature requests, and we'll close this ticket here now.
