### ISSUE TITLE
website defaults to "buy now" and discourages personal use

### ISSUE THREAD

**Issue by fermulator** [wireapp/wire#192]
Noticed now that the website shows buy default a "purchase" type button, and in super hidden grey text says "download for personal use" .

This grossly discourages average people from using the platform for personal use.

I've been trying to convince family/friends and having them visit the site resulting in them thinking they _have_ to pay does not bode well.

Can we please fix the website to make it more inviting for personal use?

Most typical would be to see "personal use, free, download now" and next to it "business/enterprise, see pricing"

**Comment by DestinFaroda** [comment]
I'm also curious if free users will ever get access to standard features like basic group administration, online status etc.

**Comment by kristin-wire** [comment]
We are working on some changes to make the website clearer, and have some exciting product changes in the pipeline - stay tuned.
Your request has been logged on our internal database for feature requests, and we'll close this ticket here now.

**Comment by mcallaghan-sandvine** [comment]
Verdict/outcome?
