### ISSUE TITLE
Feature Request: Mute Group Conversation / Only Mentions for Group

### ISSUE THREAD

**Issue by adonley** [wireapp/wire#193]
Being able to disable notifications for certain groups without a "mention" would help me keep in touch with friends but not pick up my phone every time they decide to small talk.

This feature would open up your platform for everyday use, not just person to person or team usage.

**Comment by kristin-wire** [comment]
Thanks for the suggestion. You can mute conversations now, but your  suggestion to break this with an @mention is a nice one. Noted and shared.

Your request has been logged on our internal database for feature requests, and we'll close this ticket here now.
