### ISSUE TITLE
Feature Request: Quote and Emojis

### ISSUE THREAD

**Issue by snckrz** [wireapp/wire#194]
Hey! 
I have 2 feature requests: 

- Being able to quote a message to specifically answer that. (Like in Whatsapp)
- an option to open an emoji selection like this: 
<img width="458" alt="screen shot 2018-06-05 at 13 56 46" src="https://user-images.githubusercontent.com/12545163/40974595-52c85538-68c8-11e8-82e3-68d07706be67.png">

In mac it is already there via the menubar, I am not sure how it works on other OS'es, but a dedicated button for this would be nice anyways.

**Comment by kristin-wire** [comment]
Hi there,
Thanks for the suggestions. The ability to quote a message is something we've discussed internally - on our wish list for the future too.
