### ISSUE TITLE
Wire Feature Suggestion: Non redundant notifications

### ISSUE THREAD

**Issue by Blackra1n5** [wireapp/wire#195]
Hi 👋, 

I currently love wire for both personal and business. 

Because I have the applications installed on all my devices,  I am always bombarded with redundant notifications.

Adding a feature where only the last active device will receive notification first and then other devices are notified if the message isn't read in a certain amount of time. (Similar to Apple's excellent implementation on their Messages app)

Cheers!

**Comment by kristin-wire** [comment]
Hi there,

Thanks for this! I hear you...request noted in support database, and shared with the team :-)

**Comment by richpersaud** [comment]
Where can we see a list of all Wire feature requests that were:

- submitted in github or elsewhere
- accepted for feature consideration
- rejected 

Along with priority, number of votes, or other metadata that can normally be found in github?
