### ISSUE TITLE
Features request/suggestion

### ISSUE THREAD

**Issue by twosky2000** [wireapp/wire#20]
Hey,

I love the app and it's really nice to see that someone brings innovation to the messenger.

So for my requests:

- Bring the email registration to Android and iOS. I known that this was a feature of wire but it took me half a year to know where it is. Other solutions would be a FAQ entry or a unfiltered registration on the website.
- Have a option for messages to specific devices. This does most sense on for bot's so you can have wire on insecure devices (family access, etc.).

Best regards
Twosky2000

**Comment by wmengli** [comment]
Hi @twosky2000 

So glad to hear that you love Wire and sorry for taking so long to reply.

- Email registration on mobile: Something similar in our to-do list now

- Not in the plan but will log it in our feature request system

We will close it for now and feel free to contact us for other questions. Thanks!
