### ISSUE TITLE
Feature Request: Self-Messaging

### ISSUE THREAD

**Issue by AdamDenoon** [wireapp/wire#209]
I know this is typically handled by a note-taking app, but sometimes I like to text things to myself to remember them, or see how a message will look to the recipient. Most messaging apps I've used allow this, and would be a nice, convenient way to keep encrypted notes on a server.

**Comment by cardassian-tailor** [comment]
Hello, 

This is already possible. Please see: 

https://support.wire.com/hc/en-us/articles/360000334229-How-can-I-create-a-conversation-with-myself-

**Comment by fungs** [comment]
Nice, didn't know that! Probably not the best way to sync text and data but I think there is nothing wrong with it.

**Comment by AdamDenoon** [comment]
Excellent! Exactly what I was looking for :) Thank you!
