### ISSUE TITLE
Adding Proxy Setting (SOCKS)

### ISSUE THREAD

**Issue by Deathsbreed** [wireapp/wire#22]
Those of us who are concerned with our privacy (something that Wire claims to have very much in mind) tend to like using anonymizing networks such as [TOR](https://www.torproject.org/) or [I2P](https://geti2p.net/en/) in order to hide our IP address and location. Many other [free](https://en.wikipedia.org/wiki/The_Free_Software_Definition) instant communication tools have support for proxies.

I am not sure of whether the web version works with TOR (I do not use a browser that is compatible, according to the webpage) nor if the mobile apps already have this feature (although I doubt it considering this tends to be something that comes to desktop first, in general). However, it for sure is not available in v2.12.2729 of the desktop app.

A temporary solution for GNU/Linux users is to use `proxychains` configured to use TOR simply running `proxychains wire`.

**Comment by alugarius** [comment]
I am for it!

**Comment by mythsunwind** [comment]
You can try to use the `--proxy-pac-url` command line argument from Electron to specify a proxy pac file.

**Comment by wmengli** [comment]
Hi,

This is unfortunately not planned at this stage but doesn't mean we will rule it out totally. We will close this for now and add it to our internal feature request system instead.

Thanks again for the suggestion and feel free to contact us for other questions.

Best wishes,
Wire Support Team

**Comment by Yuri-RUS** [comment]
Please add the Proxy settings. ILV blocked part of ip Wire. and a permanent loss of connection and it is not possible to send messages normally.

**Comment by mythsunwind** [comment]
Please see https://support.wire.com/hc/en-us/articles/115005697189-How-I-can-connect-through-a-proxy-server-on-desktop- on how to configure the desktop application to work with a proxy

**Comment by Yuri-RUS** [comment]
Thanks for the answer. But I use Wire on Android devices. And I have to use the Proxy Droid application to work through SOCKS5 Proxy. But it does not always work stably. This possibility is very lacking in the Wire itself.
