### ISSUE TITLE
Public rooms and a room searchable directory

### ISSUE THREAD

**Issue by alugarius** [wireapp/wire#23]
I like wire, but I only can use it if I get friends to use it.
On Riot/Matrix there are people and groups that are in a searchable directory. So it also kinda behaves like a social network.
If I create a group I want to decide if I want it public or private, I want to make a link that I can share for others to join.I want others to be able to search for my group without knowing me. I'd like to set tags.

I'd like if Wire also could add that so I can meet new people and have fun using it, also new users could get into Wire out of the box.

Also Wire support could be done by the community.

**Comment by alugarius** [comment]
I see more and more people complaining about beeing alone. with Otto The bot as the only contact.
Wire gets a feel of depression. Id like to meet communities with Wire.

**Comment by avently** [comment]
Yeah, guys, i tried to find a Wire's rooms in Google but nothing. For now not so much people use Wire. This is bad. Give us a way to connect with each other via public rooms, please. Or maybe you can create a public directory (just page at Wire.com) where people can share links to their rooms. And admin should approve an access to this room for any new user after creating a 1-to-1 conversion. Maybe in public room we shouldn't see some details of profile like email/phone etc (no private information at all. Just name, for example).
What do you think about it?

**Comment by wmengli** [comment]
Hi @alugarius and @avently, 

Sorry to tell you that we don't have a public chat rooms in the roadmap as we are focusing more on privacy.  We will close this for now and will add this to our feature request system.

Thank you and feel free to contact us again for other questions!

Best wishes,
Wire Support Team

**Comment by EchedeyLR** [comment]
Any update about it now?

**Comment by abbilaly** [comment]
New
