### ISSUE TITLE
Feature request: delete totally a contact from own list

### ISSUE THREAD

**Issue by dinzin** [wireapp/wire#230]
Would be a basic feature but here isn't implemented yet!
It's strange not to be able to completely erase one contact. I also ask to implement this new option as soon as possible.
Thank you!

**Comment by venuc** [comment]
Possible duplicate: https://github.com/wireapp/wire/issues/206

**Comment by Aikatsui** [comment]
https://github.com/wireapp/wire-webapp/issues/11198
