### ISSUE TITLE
Feature request: Quote Reply

### ISSUE THREAD

**Issue by Dexwell** [wireapp/wire#235]
This feature is really necessary. 

In many popular IM alternatives you can Quote Reply by pulling a message to the right and releasing. This eliminates a lot of confusion when multiple answers are received or multiple people are talking.

WhatsApp example (sent):
![WhatsApp example (sent)](https://cdn.ndtv.com/tech/images/whatsapp_for_android_message_quotes_replies_blurred.jpg)

Telegram example (composing):
![Telegram example (composing)](https://telegram.org/file/811140973/3/Y_QnykDVz4Y/8547554d387eb8c34b)

**Comment by lucilacaranza** [comment]
This will be released very soon ;)
Stay tuned for updates.
Cheers and have a good weekend.

**Comment by Dexwell** [comment]
@lucilacaranza I saw on desktop 😍 Thank you and looking forward to iOS release!
