### ISSUE TITLE
Feature Request: Create a link to a Wire group

### ISSUE THREAD

**Issue by RomeoKiloAlpha** [wireapp/wire#241]
I saw another request from March which states that this feature would come soon (#173 - closed).

It would be really usefull, if you could just provide a link to a group instead of adding everyone manually.

Brgrds

**Comment by lucilacaranza** [comment]
Hello,

This is possible on Wire Pro - via Guest Rooms: https://support.wire.com/hc/en-us/articles/360000574069-Pro-How-can-I-share-a-link-to-join-a-guest-room-group-conversation-in-my-team-

Best!
