### ISSUE TITLE
Privacy feature request: alias accounts/handles

### ISSUE THREAD

**Issue by 0ki** [wireapp/wire#25]
The weakest link in wire security is actually the social network you build as more and more of your  acquaintances adopt wire. Sure, seeing who is friends with who (how many friends are in common) is a useful and trust-building feature, but seeing as one of the selling points of Wire is anonymity (no phone number required), I see a problem there.

I've come to offer a solution. *Users should be able to create aliases with randomized handles¹ which are only linked to their account on their devices (e.g. user can be contacted using any of their aliases), but for other they appear like separate accounts.* This way only those with whom I shared my specific alias will be able to see the "friends" of that alias.

¹ handles should be randomized in order to prevent this being used for easy handle-hoarding.

**Comment by oscalation** [comment]
I have asked for this in the past. I need, very much so need, handles on wire. Any ability to have an additional handle would be a start.

**Comment by raphaelrobert** [comment]
You can't see how many common friends you have with someone on Wire anymore, it was deactivated a while ago.

**Comment by 0ki** [comment]
I think is is solved now.
