### ISSUE TITLE
(2017 article) Contacts in plaintext??

### ISSUE THREAD

**Issue by pdjpdjpdj** [wireapp/wire#254]
Hi Wire team,

I came across this link  [(2017) Secure Messaging App Wire Stores Everyone You've Ever Contacted in Plain Text](https://motherboard.vice.com/en_us/article/gvzw5x/secure-messaging-app-wire-stores-everyone-youve-ever-contacted-in-plain-text) and was wondering whether this is still the case. If not when did it change and how did you manage that? I'm just interested in how this is atm before signing up.

Kind regards

**Comment by raphaelrobert** [comment]
Hi @pdjpdjpdj,

The title is a bit misleading, we explain our choices in more detail in this blog post: https://wire.com/en/blog/secure-messenger-product-design-decisions/

For the future we invest in [Messaging Layer Security (MLS)](https://mlswg.github.io/), a new standard for end-to-end encrypted secure messaging, which we co-develop with other companies in an IETF workgroup. With MLS group membership is managed on the end-to-end encrypted protocol layer and therefore doesn't have to be stored by the server anymore.

**Comment by marcoconti83** [comment]
I hope @raphaelrobert 's answer was clear, I'll close this, feel free to reopen if you have more questions.
