### ISSUE TITLE
Instant messages not instant (taking hours to arrive)

### ISSUE THREAD

**Issue by unknownterritory** [wireapp/wire#255]
Hi,

I love Wire's concept and I had my family trying it out 5 people (4 adults and 1 kid) on several devices (android phones, windows and linux computers). We have been experiencing significant delays on the delivery of the messages, sometimes hours long).

We have made sure that the apps on our cellphones are not listed in any power save / performance enhancing applications and that they are allowed to notify, push and receive at any time. We have the desktop application installed on windows 10 and linux Pop!-OS and linux ubuntu 18.04 powered computers.

Right now, as an example, I sent messages to my wife, on her android. She received them hours later. Meanwhile, we have exchanged messages through my computer to her android. These do not show on my own android.

I am happy to help debug and provide more information. Let me know what other information I should provide.

**Comment by unknownterritory** [comment]
Mmm, I'm realizing I had failed to find a support page about related issues that contains steps that we might not have yet tried: https://support.wire.com/hc/en-us/articles/203624294-What-can-I-do-if-I-m-not-getting-any-notifications-on-Android-

We'll try all the recommendations in that file. Meanwhile I'll be closing this issue.

**Comment by E3V3A** [comment]
@unknownterritory 
Did you resolve the problem?

**Comment by unknownterritory** [comment]
We did.
The link proved useful. The problem resided on the Android side. It does have too many settings with the potential to interfere in effective communications and notifications, including two different ways of disabling apps to do their thing with the intent of saving battery, which is annoying. Once exceptions were open for Wire in both, communications resumed normally.
