### ISSUE TITLE
Status page for wire service

### ISSUE THREAD

**Issue by twosky2000** [wireapp/wire#26]
I had tested wire with my friend and had different response time when sending a message.
A status page like https://twitchstatus.com/ would get clarification where the problem lies.

**Comment by wmengli** [comment]
Hi @twosky2000 
Sorry for taking so long to reply. We are not considering this for now but maybe something for the future. We will close this for now and log it into our feature request system.

Thank you and feel free to contact us again for other questions!

Best wishes,
Wire Support Team
