### ISSUE TITLE
Lock rec button for long audio message (solution found)

### ISSUE THREAD

**Issue by GCamp6** [wireapp/wire#263]
Hello,
in the mobile app I think it would be very convenient to have the possibility to record long audio messages without keeping pressed the microphone icon.
I've seen that "_press+scroll up_" sends the message.
Maybe a way to implement it could be changing to "_press+scroll 45° left_" for sending and "_press+scroll 45° right_" for keeping on recording.

Cheers

**Edit**
I just realized that with a short tap on the microphone icon it is possible to do exactly that, with also access to the distortion effects list

**Comment by marcoconti83** [comment]
Glad you found a solution!
