### ISSUE TITLE
Wire desktop and mobile parse links differently

### ISSUE THREAD

**Issue by ggabarrin** [wireapp/wire#264]
When sending URLs like the one below, wire desktop and mobile versions render links to 2 different URLs:

`http://www.google.com?"test`

- [Android](https://github.com/wireapp/wire-android)
When tapping the link, it goes to `http://www.google.com`, ignoring the `test` part.

- [Desktop](https://github.com/wireapp/wire-webapp)
When clicking the link, it goes to `http://www.google.com?"test`, including the `test` part.

The issue probably exists because there's no slash (`/`) at the end of `google.com`.

**Comment by marcoconti83** [comment]
Hi @ggabarrin ,
thanks for the report. We are currently working on some changes to link handling on Desktop and how it interacts with Markdown, we will revisit this once those changes are rolled out

**Comment by marcoconti83** [comment]
Hi @ggabarrin ,

This looks fixed now. With the latest Desktop version, if I type `http://www.google.com?"test`, the link is now only `https://www.google.com`.

Please reopen if it still doesn't work for you.
