### ISSUE TITLE
Using Wire's auth as a single sign-on into my application?

### ISSUE THREAD

**Issue by segahm** [wireapp/wire#27]
Is there a description of how Wire's Authentication works? I would like to use Wire's authentication to authenticate users into my application on the same domain that I am hosting the chat client. Two questions:

How do I grab user's identifier?
How to forward users for authentication with pre-filled email/phone information?

**Comment by kim** [comment]
I'm not sure I fully understand what you are trying to do, could you describe it in a bit more detail? Are you looking for OAuth-style authorization to Wire servers? What do you mean by "hosting the chat client" - did you build your own application on top of or embedding the Wire (web?) client?

**Comment by segahm** [comment]
I build the source code from wire web client, and hosting it on my own domain, where I also host another non-wire service. I would like the end-user experience to be a smooth one, without changes to how Wire does its own authentication. OAuth-style authorization could be one solution - yes. But so as anything that would let me either pass login credentials to Wire from a 3rd party tool OR pull Wire auth token with the 3rd party app.

**Comment by raphaelrobert** [comment]
The authentication mechanism is described in section 3 of the [Security Whitepaper](https://wire.com/privacy#transparency).

**Comment by wmengli** [comment]
Hi @segahm , we will close this for now. Feel free to contact us again for other questions. 
Thanks!

Best wishes,
Wire Support Team
