### ISSUE TITLE
How do Windows versions send emojis without enabling the touch keyboard?

### ISSUE THREAD

**Issue by qrong503** [wireapp/wire#277]
Hi 👋, 

thanks for reaching out!

If you are reporting a bug or have an issue for a specific platform or project, please open the issue in the corresponding repository:

- [iOS](https://github.com/wireapp/wire-ios)
- [Android](https://github.com/wireapp/wire-android)
- [Web App](https://github.com/wireapp/wire-webapp)
- [Server](https://github.com/wireapp/wire-server)

**Comment by mythsunwind** [comment]
Use a colon `:` following another character to see an emoji chooser. For example: `:cat`
