### ISSUE TITLE
Linux startup parameters

### ISSUE THREAD

**Issue by TeeSeaLion** [wireapp/wire#278]
I am using Linux Mint Cinnamon DE on a laptop. I have the wire desktop app set to run at system startup. Can you please provide LINUX specific instructions on how I can have it connect to a proxy server at automatic startup? I have it working in windows but am not sure where to put the proxy parameters for a Linux system. I have a system wide proxy set in Mint, will it use this proxy by default? Can this be specified on the command line auto startup? How?

Thanks

BTW: It would be nice if there were a proxy configuration interface similar to the way Firefox browser allows:
No Proxy
Auto Detect
Use System Proxy Settings
Manual Proxy Configuration

**Comment by mythsunwind** [comment]
You should be able to use a proxy by adding following parameters to your auto startup:
`--proxy-server='<ip:port>'`

**Comment by TeeSeaLion** [comment]
Thanks, That worked.
