### ISSUE TITLE
Swagger API - Is the JSON already generated?

### ISSUE THREAD

**Issue by segahm** [wireapp/wire#28]
In the code there are references to the swagger-ui. Seems like the code supports Swagger code gen. What is the url for generating swagger API documentation?

**Comment by kim** [comment]
Each of our services provides Swagger v1.2 API docs of the endpoints it supports, generated via the [swagger](http://hackage.haskell.org/package/swagger) Haskell library. For example:

https://github.com/wireapp/wire-server/blob/develop/services/galley/src/Galley/API.hs#L354
https://github.com/wireapp/wire-server/blob/develop/services/galley/src/Galley/API.hs#L435  

We do not currently provide a public Swagger UI.

**Comment by david-wire** [comment]
@segahm closing this unless you need any additional information.
