### ISSUE TITLE
Otto the bot seizing chat with multiple messages

### ISSUE THREAD

**Issue by drbene** [wireapp/wire#29]
Hi, just yesterday Otto the bot suddenly seized a multi-user-chat which was opened months ago. He does not stop posting stuff like gifs, audiofiles and messages. Bug or our mistake?
Wire App iOS 2.33 (2811) on my end.
Best regards,
drbene

**Comment by teller** [comment]
What do you mean by "seized"?
Was Otto already in that chat and suddenly started posting things?

**Comment by teller** [comment]
Fastest is to just remove him from the conversation.

**Comment by drbene** [comment]
Ah ok. My fault. Just realized, my dad put him into the conversation yesterday. Did not see that before posting here. Sorry and thanks for the fast reply! Disturbing little guy this Otto ;-)
