### ISSUE TITLE
Feature request: Option for 'send to verified chats only'

### ISSUE THREAD

**Issue by xychix** [wireapp/wire#30]
Playing with extra devices and removing them all the time we notice that it's easy to miss the shield in the top of the screen on one of the devices. Once this is the case there seems to be no further notice on that specific device when extra keys are added to a conversation.

I'd love to be able to block outgoing messages to non-verified keys
- in general
- on group base

One of the two would be good enough. It would however have to be implemented in all clients  i guess?

**Comment by Namnodorel** [comment]
I agree that this would be useful, especially with security as a key feature in Wire. It also doesn't seem hard to implement...

I'd vote for maybe a popup when sending messages to unverified clients:

"The following participants are not verified yet:
[Bob]
[John]
[whoever]

Do you want to send the [message/image/...] anyways?

[(  ): Don't ask again]

[Yes/No]"

But we'd need to store the unsend message somehow, when I just recorded a voice message and click "No", I don't want it to be lost.

**Comment by mykola-mokhnach** [comment]
@Namnodorel this feature actually works the way you described it. Steps to see this warning
1. Verify all devices (own and others) in 1:1 or group conversation 
2. Log in with your account on some other device or let other verified users to do it
3. Send a message to this conversation/make a call from one of your previously verified devices

Now you will see the warning overlay, where you can ignore it and send the message anyway or cancel sending. The warning will not appear again once ignored and the conversation will be considered as degraded now.

**Comment by xychix** [comment]
@mykola-mokhnach that is clear, did extensive testing on that, I still would like to protect myself against human stupidity by having all, or certain groups set to 'send to verified keys only'.

Another option would be to have more than just 'not the shield' on top of the chat (for example print all text red when 1 or more keys aren't verified.), still prefer an option to hard block encryption with unverified keys.

**Comment by Namnodorel** [comment]
Okay, my bad... Sorry for the confusion

**Comment by wmengli** [comment]
Hi all! Sorry for taking this long to follow-up on this issue. 
@xychix, we are not considering this now as we are focusing on other priorities. However that does not mean this won't change for the future and we will add your suggestion to our feature request system.
We will close this for now and feel free to contact us for other questions. 
Thanks!

Best wishes,
Wire Support Team
