### ISSUE TITLE
[Linux] dropdown is black but options can be selected

### ISSUE THREAD

**Issue by sonic2kk** [wireapp/wire#31]
When clicking on the option for microphone or speakers in the new Linux client the dropdown menu is black. However the option is there and I can click on it and select it.

![screenshot from 2017-04-19 12-58-17 copy](https://cloud.githubusercontent.com/assets/7917345/25179053/2c7e0498-2500-11e7-9101-b7ee0cd884e0.png)

![screenshot from 2017-04-19 13-01-23 copy](https://cloud.githubusercontent.com/assets/7917345/25179140/7f5065ee-2500-11e7-917f-beec741ce474.png)

**Comment by mythsunwind** [comment]
Closing dublicate of https://github.com/wireapp/wire-desktop/issues/520
