### ISSUE TITLE
Anonymity in Wire

### ISSUE THREAD

**Issue by ElvisPresly** [wireapp/wire#32]
Sources can be read here: https://github.com/wireapp/wire-desktop/issues/278

You seek to make Wire the safest messenger, but don't react to a problem!

  We will present a situation: if the hacker, the swindler, or just the person who wants to learn about the victim more information.

He will add 1 (one) contact (victim) and by means of search (by means of a-z) will see all friends (business partners in business) the victims.

About what safety can there be a speech here?

I consider that it is necessary to make a checkbox which has to be by default switched off and if the person doesn't care for the safety, he can include it in settings.

**Comment by teller** [comment]
This is no longer possible.

**Comment by ElvisPresly** [comment]
@teller very capacious response!

**Comment by ElvisPresly** [comment]
@teller I didn't understand what you mean?

**Comment by teller** [comment]
The use case you described is no longer possible.

**Comment by ElvisPresly** [comment]
@teller Unimportant by what method it will be corrected. Important that to a problem paid more attention, and corrected it. You understand that it is a hole in anonymity and safety?

**Comment by teller** [comment]
Looks like I'm not clear enough - it's impossible to get the user relationship data any longer.

**Comment by ElvisPresly** [comment]
@teller Give me your wire id, and confirm request for adding in friends. And I will be able to call all your contacts in Wire.

**Comment by teller** [comment]
I'd do that but I've hit the 1000 connection limit and can't accept new connections, sorry. I'm sure you can test with a 2ndary dummy account.

**Comment by dkovacevic** [comment]
here use mine: @dejan

**Comment by ElvisPresly** [comment]
@teller I tested, and a problem still on a place. I wanted to prove to you because you dont trust.

**Comment by ElvisPresly** [comment]
@dkovacevic I have sent a request for @dejan, I wait for confirmation

**Comment by dejan** [comment]
Guys, please don't use GitHub's @dejan handle. I'm keep getting spammed from this project :)

**Comment by dkovacevic** [comment]
Sorry for that :(. @ElvisPresly I did not get any request from you. Are you sure you are sending to a user with username=dejan?

**Comment by ElvisPresly** [comment]
see @presley7
