### ISSUE TITLE
Help understanding

### ISSUE THREAD

**Issue by tooknie** [wireapp/wire#331]
Hi,

I joined wire and installed the android app for me and my daughter - she uses it to contact her friend, I was intending to use it to contact a friend myself but never got round to it, so my profile remained blank on my phone, with no contacts.

However, a username candyfloss85 suddenly appeared one day.  I didn't know who it was and couldn't delete it so I blocked it. It is now causing me grief as my partner thinks I have been covertly chatting with some woman, she considers this is backed up by looking at the data usage for the app earlier in December. Which shows a day where 608kb was transferred between the app and the server.  I think this might have been the day that I looked at the profile, but I didn't send a message - is there either;

1. a way to confirm no messages have ever been sent (I'm not the content of messages as I understand the platform is encrypted, just whether any were sent.
2. a way to identify who Candyfloss85 is?  I have read that the app auto invites people who are in your phone contact list so this could be how it got there, but the person is not responding on wire and I have no way of telling who it might be linked-to in the contacts.

Thank you, I understand this may be humorous to a third party but its very important to me, can you please advise?

Thanks, Tony

**Comment by marcoconti83** [comment]
Hi @tooknie ,

> a way to confirm no messages have ever been sent (I'm not the content of messages as I understand the platform is encrypted, just whether any were sent.

There is no way to verify that no message was sent - but there is also no way to verify that a message was sent.

> a way to identify who Candyfloss85 is? I have read that the app auto invites people who are in your phone contact list so this could be how it got there

If your account was not compromised and you never sent/accepted a connection request, then this is the only possible explanation: you matched with that user via your addressbooks.

> Which shows a day where 608kb was transferred between the app and the server.

Data transfer between server and client can happen at any time, even if no message was sent or received. The app will periodically check if there is any new event (messages, but also updates of connected users,...) when the app comes to the foreground, or when the app receives a "ping" via push notifications from the server.

Hope this helps!
