### ISSUE TITLE
Audio only in video call with no webcam, Group Video calls, and ability to access chat during calls

### ISSUE THREAD

**Issue by sonic2kk** [wireapp/wire#34]
It should be possible to answer a video  call on PC with no webcam. I don't own a webcam and I would like to be able to have a video call with my friends and family. This is one of the big features preventing me moving from Hangouts and Discord. It would be useful for group calls where some people have cameras and some do not.

Speaking of group calls, it would be nice if you could have group video calls as well as group voice calls. This is another feature preventing me from moving, and it is something that people I have tried to get to switch have complained about.

Finally, one rather large annoyance is the inability to access chat on mobile during a call. This applies to voice calls, video calls and group calls.

Currently, I am searching for an alternative to Google Hangouts which will be getting shut down soon and replaced with a more business-orientated successor (Meet and Chat). I checked out Telegram and it was not worth exploring at all. Horrible UI, unstable and no video calling. Right now I have my eyes set on Discord, which is slated to get video calling before the end of the year. However Discord is not as encrypted or as privacy orientated. Not that this is a huge deal for me but it is a nice - in fact a very nice - added bonus of using Wire over the other platforms. Audio quality with Wire is comparable to Discord but it does not have video and it does not have all the privacy features.

I was surprised to see that these features were not included in the service, so any chance of getting them added? If so, I can ditch Hangouts sooner perhaps.

**Comment by S3RG34NT-CYB3R** [comment]
I agree fully with the feature request here. It would be really nice to be able to group call and video. As well as access chat during a call on mobile.

**Comment by wmengli** [comment]
Hi @sonic2kk and @S3RG34NT-CYB3R 

Thank you for your feedback. Group video call, chat while calling are the frequent requests we are getting and we are considering them for the future roadmap but no ETA yet. 

Regarding the ability to answer video call without a camera, this is an interesting point. We will log it this in our feature request system. 

I am closing this ticket for now and feel free to write to us for other feedback. Thanks!

Best wishes,
Wire Support Team
