### ISSUE TITLE
[Feature request] image copy to clipboard from wire-desktop app (especially on Linux)

### ISSUE THREAD

**Issue by f4th0m** [wireapp/wire#343]
Hello,

This request was opened in wire-desktop repository, but has been closed with the comment that it can opened here and then added to the roadmap at some point:
https://github.com/wireapp/wire-desktop/issues/351

Please consider this, cause currently the only option for an image is to download, which makes it really tedious to share picture based stuff on Wire.

Thanks!

**Comment by ffflorian** [comment]
Done with https://github.com/wireapp/wire-desktop/pull/4141 and will be available with 3.20.
