### ISSUE TITLE
Make the video mirrored so it's more natural

### ISSUE THREAD

**Issue by WildYorkies** [wireapp/wire#35]
On my macbook, the web camera video is flipped.

It's more natural and normal for the video to be mirrored (as if it's a mirror).

So when you raise your right hand, you see your hand on the right side of your video feed.

(Opened here per https://github.com/wireapp/wire-webapp/issues/983 )

**Comment by wmengli** [comment]
Hi @WildYorkies 

Unfortunately this is still not in our road map yet. I am going to close this ticket for now and track it in our internal feature request system instead.

Thank you!

Best wishes,
Wire Support Team
