### ISSUE TITLE
Federation without metadata track

### ISSUE THREAD

**Issue by akreuzkamp** [wireapp/wire#36]
Hi,

I'm writing this to ask you a question about metadata in federated messaging systems and how to avoid them. It's not an issue in the stricter sense, not even so much about wire itself (but might though apply to it) but rather about the concept itself. As I don't know, whom to ask this, I decided to directly address the questions to some experts, thus opening this issue, because it's the only communication channel I found to talk to you wire-devs. 

All federated communication channels I know (namely e-mail, XMPP and Matrix) route the messages through four nodes: `Alice (A) -> Alice's provider (P1) -> Bob's provider (P2) -> Bob`. Thus, even with e2ee, both P1 and P2 know exactly who communicates with whom. As a consequence, Alice has to trust Bob's provider in order to communicate with him. To me, routing the message through P1 seems 
dispensable.

I wonder, and that's my question, why this indirection is needed. Recently, I've been thinking about a federated messaging system, that would lift the need to trust one's partner's provider, by simply removing the indirection through the own provider:
Alice sends an e2ee-message to Bob's provider (P2) without authenticating herself (possibly though authorizing herself). P2 now knows that *someone* wrote to Bob, but not who. Bob's device will be able to decrypt the message and thus know who wrote (using e.g. DANE Bob could verify the origin). So far, 
Alice didn't gain any privacy. Now Bob replies. He will send an e2ee-message to Alice's provider (P1), again without authentication. Only Alice will be able to decrypt the message and know the author. Here the difference happened. As P2 didn't receive the reply, P2 won't even know, that Bob replied even less 
whom he replied to and thus who wrote in the very beginning.

In fact if Alice and Bob shared the same provider, the provider would be able to trace the communication. That means, you'd still have to trust your own provider about the metadata, but never need to trust the provider of others.
As this concept isn't too far-fetched, I'm wondering why I couldn't find any documentation about it and why it seems nobody ever tried to implement it. Are there any obvious design flaws I don't see or any other issues, political or technical reasons? I'm neither experienced in designing network protocols nor 
in writing server software (I'm a C++ developer), so I will probably never be able to implement such a system. I'm just a privacy aware citizen, hoping to see this kind of communication channel to appear some day.

Imho if e.g. wire would implement this, it would have the potential to become the one and only really private online-communication channel.

Thanks in advance for your reply. :)

**Comment by raphaelrobert** [comment]
Hi,

Thanks for your input, this is however not strictly related to Wire at this point. We will explore federation concepts in the future, but we haven't sorted out all the details yet.

**Comment by akreuzkamp** [comment]
Hi,

thanks for the answer. :) As I've written, it's more of a question and not so much a feature request. In case, you haven't decided on how to do federation yet, I'd be glad though if you decided to take my concept into account. :)
Else, in case you know, why this wouldn't work, I'd be interested in that feedback.

**Comment by wmengli** [comment]
Hi @akreuzkamp 

I am going to close this now. Feel free to contact us if you have other questions.

Best wishes,
Wire Support Team
