### ISSUE TITLE
Dark Theme shuts off in Desktop versions when going into sleep mode, upon restart of system and app etc. 

### ISSUE THREAD

**Issue by macexpertsusa** [wireapp/wire#364]
The Dark Theme in preferences/options shuts off and reverts to white when machine sleeps, after restart of OS, after restart of application. At first it was an occasional issue but now it is persistent.

Affected platforms  Windows 8.1 and Windows 10 that I know of. Have encountered this on multiple systems/installs and a fresh install of Win 10 in a VM.

In settings the Dark Theme will no longer be selected when the issue occurs so the preferences settings maybe are not staying persistent or being corrupted somehow. 

Android doesn't seem to be affected.   I don't have iOS/MacOS presently available to test nor a Debian install.

Problem has been ongoing since the later half of 2020 - I had found a post on it previously but can no longer find it. I am fairly certain I chimed in on that post but it's not in my profile history as well. Maybe it was deleted? Since the issue never got resolved but became persistent instead I came to check on any progress/notations in the thread only to not find the thread is not here.  I also do not see new any open tickets on this issue.

Regards to all!

**Comment by Bust3D** [comment]
Same here,
Dark Mode after Exit or Restart Wire app in Windows doesn't preserve the settings.

**Comment by macexpertsusa** [comment]
This appears to have been resolved.
