### ISSUE TITLE
Bug/Featurerequest: If logged in to often, nothing works, but no info is shown either

### ISSUE THREAD

**Issue by schlichtanders** [wireapp/wire#37]
Dear wire-team,

unfortunately I have crucial problems now that I start using wire. On of them seems to be that if you once have problems, then your account seems to get blocked. It is really great that you care about security, however would really like to encourage you updating the UI everywhere to also tell your users.

Look here (also mentioned here https://github.com/wireapp/wire-webapp/issues/45#issuecomment-298873753):
![wirewebloginproblems2](https://cloud.githubusercontent.com/assets/4255480/25660112/16424df4-300b-11e7-8682-4eabfe202753.PNG)
this screenshot shows that I cannot login, however **nothing** is shown that something prevents me from login (seemingly I have logged in to often in sequence)

The fact itself that I get blocked by having logged in to often and not seeing any way out of there is horrible and will prevent a crucial number of potential users to just go away again. Even worse, my initial impression of wire being more elaborate already is now lost to a big deal. Hence, I think this is a really crucial point which should get high priority to be solved.

Suggested solutions:
- inform the user about you blocking them just because one of your algorithms thought this would be a good idea (of course also inform them if you do it manually)
    - write them a mail about the decision taken and what the next steps are
    - give a feedback on your webpage, also including next steps (e.g. how long the account is blocked now, who to contact, ...)
- give them the option to verify and unblock their account by additional verification mails, stuff, you know this better than me. If I can sign up in a safe way, then I can also reverify that everything is good in a safe way.

I hope this very annoying current behaviour is fixed soon and future users don't have to bother with this, but it just works (and I myself would like to advertise wire as "it just works", too, currently I am again afraid to recommend wire at all because of this, unfortunately)

Thanks a lot for this very awesome project and for pushing it forward!

**Comment by schlichtanders** [comment]
The described problem happens in both ``app.wire.com`` and the windows application (more I haven't tested), no feedback, no info, no option, nothing, just not working

**Comment by wmengli** [comment]
Hi @schlichtanders 

Seems you were able to login as you mentioned here https://github.com/wireapp/wire-webapp/issues/45

I am going to close the ticket for now. Feel free to contact us again if the problem still pending for you. Thanks!

**Comment by schlichtanders** [comment]
as said in wireapp/wire-webapp#45 only the blocking disappears after one day - *magically*.

An information that ``"the account is blocked for one day because of ..."`` does not appear anywhere. Please consider adding such an information.
