### ISSUE TITLE
Possible security risk by auto-adding new devices

### ISSUE THREAD

**Issue by fungs** [wireapp/wire#38]
Well, first of all I'm not sure if this is the right repo to report these kind of things. Maybe, there should be a more general or pan-repository issue tracker.

There exists the theoretical possibility to sneak into a conversation and capture private information by using the login credentials (acquired by some means like a pishing attack on the web client) for a short period of time before the users gets notified via email, that a new device was added. Also, the attacker could potentially remove all other devices from the devices list and do other destructive things. Ideally, a new device would only be linked once it has been confirmed, either by a trusted device (client gui) or by a confirmation link in the email. Therefore, it would be best if two factors were required to add a new device to the device list, at least as an option in the account settings.

Such an attack might be rather unlikely but for high frequency conversations with confidential information it can be a real scenario.

**Comment by raphaelrobert** [comment]
The email notification is sent out immediately.

We cannot protect users against any kind of social engineering attack, but we are considering some changes to give users better control in the future.

**Comment by fungs** [comment]
Damage can be low or high, depending on the situation. Say, someone is in a confidential group discussion and goes on vacation, the information leak can exist for weeks. For instance, targeting a politically prosecuted oppositional, is would be relatively easy for state agencies to capture the login credentials (we all know that the SSL certificate infrastructure is fundamentally broken). This would under normal circumstances not compromise the content of the conversations due to the encryption scheme, because the private keys remain secret.

The question is, whether you want to compromise the strong encryption scheme by a small convenience function.

**Comment by raphaelrobert** [comment]
> we all know that the SSL certificate infrastructure is fundamentally broken

We started to introduce public key pinning in the desktop apps, mobile clients will follow.

But as I said, we are considering additional changes.

**Comment by mythsunwind** [comment]
AFAIK the theoretical possibility to sneak into a conversation and capture private information (by using the login credentials for a short period of time before the users gets notified via email) is only possible, if you do NOT use the mechanism to verify a conversation. If you have verified all your devices and the devices of the participant, you will get a dialog before you send a message that informs you about a new device and you can cancel the sending of the message.

**Comment by fungs** [comment]
@mythsunwind: thanks, I didn't know

**Comment by david-wire** [comment]
@fungs closing this unless you need any additional information.
