### ISSUE TITLE
Android - v3 to v4 message history lost

### ISSUE THREAD

**Issue by MacGurus** [wireapp/wire#385]
wire app android reloaded updated and despite spending a lot of time apparently 'migrating' messages no messages were migrated on either of two accounts - the account information and contacts seems to have migrated however

the data size in the phone is still several GB but not a single message appears in the application after the latest update

any ideas? any way to initiate a re-migration or did it just toss everything into the ether?

- [Android](https://github.com/wireapp/wire-android)  <<can't post here anymore or the new one  here https://github.com/wireapp/wire-android-reloaded

**Comment by tmspzz** [comment]
> any way to initiate a re-migration or did it just toss everything into the ether?


You old messages as safe and sound. Nothing is tossed, the old database is not removed.
You can re-initiate the migration manually from **Settings > Debug Settings > Start Migration from...**

What we are hearing is that for some users the messages are migrated but they don't display, or the hold history flashes briefly in the conversation upon receiving a new message.

We would be more than happy to look into your problem if we could actually reproduce it. We haven't been able so far.

Would you be available to be contacted by our engineering team and possibly sit with them to solve the issue?

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hello,

Same problem here 😢 All my "multiple participants conversation" are OK, but histories from my "1 to 1 conversation" are not displayed. I re-initiated migration with the option but nothing changed.

🌻

**Comment by HerroBert** [comment]
I have the same problem and rerun of migration do nothing.
BTW my backup size is below 10MB.

**Comment by tmspzz** [comment]
Hello, and thanks for your initiative.

I want to repeat once more that (unless you uninstalled the app), no data is lost. Your messages are still there (altho, you might not see them).

Please join our open testing program via https://play.google.com/store/apps/details?id=com.wire or https://play.google.com/apps/testing/com.wire

Once we release a new version you will get it before the public. We will add options that will make reporting info with this particular issue easier.

**Comment by bouncecoin** [comment]
Same issue. Not a single message from one to one conversations has migrated. I'm not on the beta (v4.1.2(6407703)-prod), I had my app updated automatically on Android last night. I still have messages from the groups. I have manually started the migration from the Debug-Settings several times and it runs for a few seconds and stops. I have over 140k messages. I wonder if some database limitation is being reached and the migration simply stops. Perhaps you are trying to reproduce the error on a small test sized database and missing the problem.

**Comment by tmspzz** [comment]
We believe the error is in the related to a specific version of the former android application https://github.com/wireapp/wire-android-reloaded/pull/1756

**Comment by tmspzz** [comment]
version v4.1.3 contains a fix and is available for open testing

**Comment by GitStorageOne** [comment]
> > version v4.1.3 contains a fix and is available for open testing
> 
> Does not work at all, total crash after start. Wire app is dead now...

You are probably not using the latest version.
Check for new updates (today they released 2 versions, the last one seems to work)

**Comment by HerroBert** [comment]
it was 4.1.3 (6466165)-prod.
after update again, looking good now! all old messages seems to be there...

**Comment by tmspzz** [comment]
> After update, the old messages reappear, but now, when it reaches back in the list, Wire will freeze. Android will respond with "App is not Responding" message. I click "Wait for it to Respond". Then after about 20 seconds, then the "Wire App Closed".
> 
> Getting there, but now there is a new problem. I have repeated this a number of times, including after a phone reboot. Version: v.4.1.3(6467739)-prod.

Please keep doing what you're doing as many times as you can so we can see the problem bubble up in the PlayStore console

**Comment by tmspzz** [comment]
In case you are able please consider the following options to help us identify the issue:

- Option 1: in the application go to `Hamburger Menu > Settings > Debug settings > Enable logs` and reproduce the issue. Share the logs to a location convenient to you (feel free to inspect them before) and paste here or elsewhere the relevant lines (probably towards the bottom of the log) or the entire log file

- Option 2: connect your device to your computer, and with [adb installed](https://www.xda-developers.com/install-adb-windows-macos-linux/) run `adb logcat`. Reproduce the issue and paste here the relevant lines

**Comment by bouncecoin** [comment]
I caused the App crash a couple dozen times. I hope that helped the exceptions bubble up.

Back of list means when scrolling at the top. In other words, when scrolling down, or moving new messages off the bottom of the screen, showing newer message on the top.

A couple of details. When scrolling a conversation with many message, but fewer pictures, it will freeze, and start responding again about 30-60 seconds later, then I can continue scrolling.

When I scroll another conversation, with quite a few pictures, it will freeze, just like the other conversation, but never recovers and closes the app. Then the Wire background service will restart along with the message.

Logs attached. I turn on logs, scrolled the specific conversation and experienced a freeze, then subsequent crash. Restarted Wire, then Shared logs. As you can see, memory allocation is failed because <1% of the heap is free.

Phone:
- CPU: Helio G96
- GPU: ARM Mali-G57
- RAM: 8
- Storage 256
- Screen size: 6.3"
- Screen Resolution: 2400x1080
- Android: 12
- Battery Ah: 6

[wire_logs-2023-05-09.txt](https://github.com/wireapp/wire/files/11435622/wire_logs-2023-05-09.txt)

**Comment by cocoon** [comment]
V..7739 Not starting anymore, found this:

`FATAL EXCEPTION: DefaultDispatcher-worker-3
Process: com.wire, PID: 16161
net.zetetic.database.sqlcipher.SQLiteConstraintException: UNIQUE constraint failed: Message.id, Message.conversation_id (code 1555)
	at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at net.zetetic.database.sqlcipher.SQLiteConnection.executeForChangedRowCount(Unknown Source:33)
	at net.zetetic.database.sqlcipher.SQLiteSession.executeForChangedRowCount(Unknown Source:15)
	at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(Unknown Source:20)
	at q5.b.a(Unknown Source:2)
	at q5.f.R(Unknown Source:7)
	at q5.d.c(Unknown Source:28)
	at q5.d.E(Unknown Source:12)
	at om.b$a.c(Unknown Source:891)
	at q5.d$a.f(Unknown Source:119)
	at km.b$a.onUpgrade(Unknown Source:9)
	at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getDatabaseLocked(Unknown Source:293)
	at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getWritableDatabase(Unknown Source:2)
	at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getWritableDatabase(Unknown Source:0)
	at q5.d$c.a(Unknown Source:6)
	at vo.l.getValue(Unknown Source:20)
	at q5.d.g(Unknown Source:2)
	at q5.e.a(Unknown Source:4)
	at q5.d.c(Unknown Source:14)
	at q5.d.E(Unknown Source:12)
	at jm.c.<init>(Unknown Source:339)
	at jm.e.b(Unknown Source:131)
	at ji.b.a(Unknown Source:47)
	at ji.e.a(Unknown Source:8)
	at ho.b$a.R(Unknown Source:2)
	at ho.a.apply(Unknown Source:7)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1716)
	at ho.b.a(Unknown Source:12)
	at li.x0.<init>(Unknown Source:56)
	at li.z0$a.a(Unknown Source:256)
	at ho.b$a.R(Unknown Source:2)
	at ho.a.apply(Unknown Source:7)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1716)
	at ho.b.a(Unknown Source:12)
	at li.z0.b(Unknown Source:18)
	at yg.g.e(Unknown Source:13)
	at lg.b.b(Unknown Source:108)
	at lg.d$b.a(Unknown Source:104)
	at lg.d$b$a.o(Unknown Source:12)
	at cp.a.t(Unknown Source:8)
	at zp.q0.run(Unknown Source:100)
	at fq.a$a.run(Unknown Source:81)
	Suppressed: zp.o0: [e2{Cancelling}@a497b45, Dispatchers.Default]`

**Comment by vitorhugods** [comment]
> 



> V..7739 Not starting anymore, found this:
> 
> `FATAL EXCEPTION: DefaultDispatcher-worker-3 Process: com.wire, PID: 16161 net.zetetic.database.sqlcipher.SQLiteConstraintException: UNIQUE constraint failed: Message.id, Message.conversation_id (code 1555) at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method) at net.zetetic.database.sqlcipher.SQLiteConnection.executeForChangedRowCount(Unknown Source:33) at net.zetetic.database.sqlcipher.SQLiteSession.executeForChangedRowCount(Unknown Source:15) at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(Unknown Source:20) at q5.b.a(Unknown Source:2) at q5.f.R(Unknown Source:7) at q5.d.c(Unknown Source:28) at q5.d.E(Unknown Source:12) at om.b$a.c(Unknown Source:891) at q5.d$a.f(Unknown Source:119) at km.b$a.onUpgrade(Unknown Source:9) at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getDatabaseLocked(Unknown Source:293) at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getWritableDatabase(Unknown Source:2) at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getWritableDatabase(Unknown Source:0) at q5.d$c.a(Unknown Source:6) at vo.l.getValue(Unknown Source:20) at q5.d.g(Unknown Source:2) at q5.e.a(Unknown Source:4) at q5.d.c(Unknown Source:14) at q5.d.E(Unknown Source:12) at jm.c.<init>(Unknown Source:339) at jm.e.b(Unknown Source:131) at ji.b.a(Unknown Source:47) at ji.e.a(Unknown Source:8) at ho.b$a.R(Unknown Source:2) at ho.a.apply(Unknown Source:7) at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1716) at ho.b.a(Unknown Source:12) at li.x0.<init>(Unknown Source:56) at li.z0$a.a(Unknown Source:256) at ho.b$a.R(Unknown Source:2) at ho.a.apply(Unknown Source:7) at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1716) at ho.b.a(Unknown Source:12) at li.z0.b(Unknown Source:18) at yg.g.e(Unknown Source:13) at lg.b.b(Unknown Source:108) at lg.d$b.a(Unknown Source:104) at lg.d$b$a.o(Unknown Source:12) at cp.a.t(Unknown Source:8) at zp.q0.run(Unknown Source:100) at fq.a$a.run(Unknown Source:81) Suppressed: zp.o0: [e2{Cancelling}@a497b45, Dispatchers.Default]`

Thank you **so much** for this stack trace, as we can understand what is happening. Although we're note quite sure _why_, we're working on an another update that should fix this and should be delivered soon.
The transition from the old to the new app is being bumpy mainly because the old app had so many bugs that a few managed to slip through for a small portion of users.

Our main goal with the new app is stability – something easy to see when performing a fresh install – but as I said, can get a bit messy when migrating from the old app. So some features might be missing at the moment, but we're working fast to bring them back in the coming updates.

Thank you for your patience and expect an update with a fix soon. Most likely still today.

**Comment by tmspzz** [comment]
> V..7739 Not starting anymore, found this:
> 
> `FATAL EXCEPTION: DefaultDispatcher-worker-3 Process: com.wire, PID: 16161 net.zetetic.database.sqlcipher.SQLiteConstraintException: UNIQUE constraint failed: Message.id, Message.conversation_id (code 1555) at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method) at net.zetetic.database.sqlcipher.SQLiteConnection.executeForChangedRowCount(Unknown Source:33) at net.zetetic.database.sqlcipher.SQLiteSession.executeForChangedRowCount(Unknown Source:15) at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(Unknown Source:20) at q5.b.a(Unknown Source:2) at q5.f.R(Unknown Source:7) at q5.d.c(Unknown Source:28) at q5.d.E(Unknown Source:12) at om.b$a.c(Unknown Source:891) at q5.d$a.f(Unknown Source:119) at km.b$a.onUpgrade(Unknown Source:9) at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getDatabaseLocked(Unknown Source:293) at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getWritableDatabase(Unknown Source:2) at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getWritableDatabase(Unknown Source:0) at q5.d$c.a(Unknown Source:6) at vo.l.getValue(Unknown Source:20) at q5.d.g(Unknown Source:2) at q5.e.a(Unknown Source:4) at q5.d.c(Unknown Source:14) at q5.d.E(Unknown Source:12) at jm.c.<init>(Unknown Source:339) at jm.e.b(Unknown Source:131) at ji.b.a(Unknown Source:47) at ji.e.a(Unknown Source:8) at ho.b$a.R(Unknown Source:2) at ho.a.apply(Unknown Source:7) at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1716) at ho.b.a(Unknown Source:12) at li.x0.<init>(Unknown Source:56) at li.z0$a.a(Unknown Source:256) at ho.b$a.R(Unknown Source:2) at ho.a.apply(Unknown Source:7) at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1716) at ho.b.a(Unknown Source:12) at li.z0.b(Unknown Source:18) at yg.g.e(Unknown Source:13) at lg.b.b(Unknown Source:108) at lg.d$b.a(Unknown Source:104) at lg.d$b$a.o(Unknown Source:12) at cp.a.t(Unknown Source:8) at zp.q0.run(Unknown Source:100) at fq.a$a.run(Unknown Source:81) Suppressed: zp.o0: [e2{Cancelling}@a497b45, Dispatchers.Default]`

version v4.1.4(6476411) available via Open testing should address your issue

**Comment by HerroBert** [comment]
I want to ask here all those testers, do you see read status? I don't...

**Comment by tmspzz** [comment]
> I want to ask here all those testers, do you see read status? I don't...

Assuming read receipts are enabled for both parties in the conversation or, in case of a group conversation they are enabled by an admin:

Long tap on the message > message details > read receipts

**Comment by tmspzz** [comment]
> I caused the App crash a couple dozen times. I hope that helped the exceptions bubble up.
> 
> Back of list means when scrolling at the top. In other words, when scrolling down, or moving new messages off the bottom of the screen, showing older messages on the top.
> 
> A couple of details. When scrolling a conversation with many message, but fewer pictures, it will freeze, and start responding again about 30-60 seconds later, then I can continue scrolling.
> 
> When I scroll another conversation, with quite a few pictures, it will freeze, just like the other conversation, but never recovers and closes the app. Then the Wire background service will restart along with the message stating the service is starting.
> 
> Logs attached. I turned on logs, scrolled the specific conversation and experienced a freeze, then subsequent crash. Restarted Wire, then Shared logs. As you can see, memory allocation is failing because <1% of the heap is free.
> 
> Phone:
> 
> * CPU: Helio G96
> * GPU: ARM Mali-G57
> * RAM: 8
> * Storage 256
> * Screen size: 6.3"
> * Screen Resolution: 2400x1080
> * Android: 12
> * Battery Ah: 6
> 
> [wire_logs-2023-05-09.txt](https://github.com/wireapp/wire/files/11435622/wire_logs-2023-05-09.txt)

we are not yet able to make sense on this, but we're keeping an eye on it.

**Comment by bouncecoin** [comment]
> > I want to ask here all those testers, do you see read status? I don't...
> 
> Assuming read receipts are enabled for both parties in the conversation or, in case of a group conversation they are enabled by an admin:
> 
> Long tap on the message > message details > read receipts

I can confirm that read receipts do not work in this new version. Both parties are enabled, and the read notification works great on the Windows Desktop app. I miss this feature.

**Comment by bouncecoin** [comment]
> 

I will test it once another new version is released. I suspect the problem will still exist in my very long message thread with lots of images. Based on anecdotal evidence, I would say there is a problem with heap allocation with lots of images during the scroll process. I'm happy to assist with this issue because I have a real-world example that will remain in existence. Perhaps logging with free heap numbers in it that I can capture again for you.

**Comment by bouncecoin** [comment]
> we are not yet able to make sense of this, but we're keeping an eye on it.

I will test it once another new version is released. I suspect the problem will still exist in my very long message thread with lots of images. Based on anecdotal evidence, I would say there is a problem with heap allocation with lots of images during the scroll process. I'm happy to assist with this issue because I have a real-world example that will remain in existence. Perhaps logging with free heap numbers in it that I can capture again for you.

**Comment by bouncecoin** [comment]
> we are not yet able to make sense of this, but we're keeping an eye on it.
>> I will test it once another new version is released. I suspect the problem will still exist in my very long message thread with lots of images. Based on anecdotal evidence, I would say there is a problem with heap allocation with lots of images during the scroll process. I'm happy to assist with this issue because I have a real-world example that will remain in existence. Perhaps logging with free heap numbers in it that I can capture again for you.

I just tested v4.1.4(6476411)-prod. Issue persists.

**Comment by tmspzz** [comment]
> > > I want to ask here all those testers, do you see read status? I don't...
> > 
> > 
> > Assuming read receipts are enabled for both parties in the conversation or, in case of a group conversation they are enabled by an admin:
> > Long tap on the message > message details > read receipts
> 
> I can confirm that read receipts do not work in this new version. Both parties are enabled, and the read notification works great on the Windows Desktop app. I miss this feature.

It this a conversation that was migrated (i.e. one of the ones that lost history)? Or a new conversation?

If you have the chance to connect to a new user or group after migration and check if read receipts work in that case, it would be of great help.

**Comment by tmspzz** [comment]
@bouncecoin 

![Screenshot_20230511_010037_Wire Beta.jpg](https://github.com/wireapp/wire/assets/196761/5acdc38b-ec54-43b4-ab37-9d266e77a29a)

**Comment by HerroBert** [comment]
> Is this a conversation that was migrated (i.e. one of the ones that lost history)? Or a new conversation?
For me it is for old and new messages.
(I can see read status in browser.)

> 
> If you have the chance to connect to a new user or group after migration and check if read receipts work in that case, it would be of great help.
I do not have any groups.
