### ISSUE TITLE
Document how to submit bug reports and feature request issues (Android app repos)

### ISSUE THREAD

**Issue by maltfield** [wireapp/wire#386]
Please document how we're supposed to submit:

1. Bug Reports and
2. Feature requests

for Wire software on Android on the relevant github repos:

1. https://github.com/wireapp/wire-android
1. https://github.com/wireapp/wire-android-reloaded

I ask because the `README.md` file for both of these repos don't mention how to submit bugs/feature issues:

 * https://raw.githubusercontent.com/wireapp/wire-android/develop/README.md
 * https://raw.githubusercontent.com/wireapp/wire-android-reloaded/develop/README.md

Note that **there is no "Issues" button at the top of these two repos**. I came *here* to report this instead, but I'm not sure if that's what I'm *supposed* to do because it doesn't appear to be documented

### (also wtf) this boilerplate issue template

Curiously, when I open an issue in *this* repo, I the issue is preloaded with the following text

 * https://raw.githubusercontent.com/wireapp/wire/master/issue_template.md

```
Hi 👋, 

thanks for reaching out!

If you are reporting a bug or have an issue for a specific platform or project, please open the issue in the corresponding repository:

- [iOS](https://github.com/wireapp/wire-ios)
- [Android](https://github.com/wireapp/wire-android)
- [Web App](https://github.com/wireapp/wire-webapp)
- [Server](https://github.com/wireapp/wire-server)
```

But that doesn't make any damn sense. When I go to the repos it tells me to go to, I can't create an issue!

# Solution

The solution to this issue is to add a section to the following files that explains how to submit bug reports and feature requests

 * https://raw.githubusercontent.com/wireapp/wire-android/develop/README.md
 * https://raw.githubusercontent.com/wireapp/wire-android-reloaded/develop/README.md

**Comment by tmspzz** [comment]
I removed the ability to open issues due to the abuse developers were subject to.

You can find in the application itself a button to report a bug. Feel free to use it to request features as well.
