### ISSUE TITLE
Publish Wire Reloaded in F-Droid

### ISSUE THREAD

**Issue by maltfield** [wireapp/wire#387]
First, I can't seem to find the ticket that's tracking the deployment of the new Wire Reloaded app? Can you please link to the GitHub issue that's tracking this?

This ticket is a request to add the new Wire Reloaded app to the F-Droid repos:

 * https://github.com/wireapp/wire-android-reloaded

As far as I an tell (again, this isn't documented anywhere that I can find) the old wire app is v3.X and the new "reloaded" version is v4.X. Is that correct? If so, can you please link me to the documentation that makes this clear??

If the above assumption is correct, then it appears that the latest version of Wire on F-Droid is the old version (`3.82.38` as of `2023-05-10`).

 * https://f-droid.org/en/packages/com.wire/

# Solution

Please update the F-Droid repos with the new android "reloaded" app

**Comment by tmspzz** [comment]
Thanks for your interest, we have plans to update the F-Droid version in the future.

We accept contributions on the matter.

**Comment by blacklightpy** [comment]
I have opened a packaging request with F-Droid: https://gitlab.com/fdroid/rfp/-/issues/2585

**Comment by blacklightpy** [comment]
The F-Droid team has asked for the build recipe, and also they've mentioned that the current flavour depends on the GMS proprietary blob, which is not allowed in F-Droid. (https://gitlab.com/fdroid/rfp/-/issues/2585#note_1665728070)

So please make an alternative for F-Droid, just like legacy Wire did.

**Comment by MohamadJaara** [comment]
android v4.8.4 is already available on Fdroid

**Comment by maltfield** [comment]
Confirmed. Wire "Reloaded" [4.8.4-20981-fdroid (100020981)] can now be downloaded from F-Droid, as of 2024-09-12

 * https://f-droid.org/en/packages/com.wire/

Thank you. I had mostly migrated from Wire to Matrix because of this outstanding issue; glad that we can still use Wire :)
