### ISSUE TITLE
Missing search option in Wire Android Reloaded

### ISSUE THREAD

**Issue by ThePirateWhoSmellsOfSunflowers** [wireapp/wire#390]
Hi,

It is no longer possible to search in conversation with the new android application. Any plan to implement it ?
Thanks.

:sunflower:

**Comment by MohamadJaara** [comment]
Hi @ThePirateWhoSmellsOfSunflowers this feature has been added to wire [version 4.6](https://github.com/wireapp/wire-android/pull/2358) which is already in open testing on the play store
