### ISSUE TITLE
Upgrade erased all previous conversation data

### ISSUE THREAD

**Issue by burdges** [wireapp/wire#394]
As I said in https://github.com/wireapp/wire/issues/391#issuecomment-1580969742 the report bug button does not work, so I'll open an issue here.

I run Graphene OS, aka stock Android, without google play services.  Wire recently upgraded, likely form https://github.com/wireapp/wire to https://github.com/wireapp/wire-android-reloaded but unsure really.

This upgrade hid or erased ALL previous conversation data without any warning, but retained the contacts list.  Is there a way to prevent this or even recover the data?

**Comment by tmspzz** [comment]
The report button opens an email intent. Check your have an application that can handle email intents.

Currently, we don't support GrapheneOS.

Your conversation history is not lost, please see https://github.com/wireapp/wire/issues
