### ISSUE TITLE
Sending files bigger than 25MB

### ISSUE THREAD

**Issue by f4th0m** [wireapp/wire#399]
Hi 👋, 

Please allow sending files bigger than 25 megs, that is kinda insane limitation that a 10 sec video clip can't be sent over this messenger. 

Thanks in advance!
Tamás

**Comment by tmspzz** [comment]
https://support.wire.com/hc/en-us/articles/208368315-Send-a-file please refer to the help article.

**Comment by f4th0m** [comment]
I am not sure how is this an answer... Yes it is limited... But why? and even if it is why so small limit? On a modern phone this means that you can't send a short video of your child, 25 megs is nothing...
