### ISSUE TITLE
[Android App] Failed to Run Wire Android App 

### ISSUE THREAD

**Issue by ysavr** [wireapp/wire#407]
👋 Hello everyone,

i already clone the [wire android](https://github.com/wireapp/wire-android), i follow the instruction

- After cloning the Android project, you have run `git submodule update --init --recursive` (to init any needed configuration within the embedded Kalium submodule project)

- There is a valid SDK path on your `local.properties` AND `kalium/local.properties` files pointing to the Android SDK folder. In Mac, that folder can be usually found under `sdk.dir=/Users/YOUR_USER_FOLDER/Library/Android/sdk`. The IDE will not create `kalium/local.properties` automatically, so you might want to copy/paste the one in the project root

but i face some error when run `./gradlew build`, how to solve this issues, thanks in advance

<img width="1672" alt="Screenshot 2024-03-05 at 11 44 13" src="https://github.com/wireapp/wire/assets/17620751/f8a2e4f4-e13b-49a3-93e9-b2714c900fc3">

**Comment by vitorhugods** [comment]
Hello @ysavr.
Which OS are you using to build the app?

We are having some issues with our setup + SQLDelight, but this is the first time I hear it is actually stopping builds.
_i.e._ these are usually logged as _error_ but the build finishes successfully.
I can kinda reproduce it on my side when building from a MacOS during the first time, but these don't show in future attempts.

<img width="1080" alt="grafik" src="https://github.com/wireapp/wire/assets/9389043/4cd0e0aa-1619-4048-b89a-4e1229fd29e9">

Could you please check the result of the build as whole?

<img width="1132" alt="grafik" src="https://github.com/wireapp/wire/assets/9389043/83b07b5f-a554-4c0d-8906-17308c27b24e">

We have a very bleeding-edge Kotlin Multiplatform setup with some instability here and there so it isn't always smooth. It used to be _way_ worse.
We are in our way to upgrade Kotlin to 1.9.20 and prepare for Kotlin 2.0, which could improve these.

**Comment by emil-wire** [comment]
Hey @ysavr what's your JDK version and setting in android studio? have you installed the android sdk and ndk?

**Comment by ysavr** [comment]
i use MacOs to build this repo

this my JDK Version that i used in android studio
<img width="1800" alt="Screenshot 2024-03-05 at 16 48 46" src="https://github.com/wireapp/wire/assets/17620751/de5d65bc-f263-4d17-9a89-af8831a8e898">

this is the ndk version that i install
<img width="988" alt="Screenshot 2024-03-05 at 16 50 02" src="https://github.com/wireapp/wire/assets/17620751/94165045-b475-4bbd-aa3f-8db3d40d82b8">

error when run` ./gradlew build` but successfull build on device
<img width="451" alt="Screenshot 2024-03-05 at 16 57 07" src="https://github.com/wireapp/wire/assets/17620751/47bd62fa-f71a-4473-9234-fcf7afc50cb4">

**Comment by vitorhugods** [comment]
Yeah, so... That is known. It's just an ignorable warning :)

Good that you can reproduce the build locally and run it.

I'll close the issue for now. Have a nice one :)
