### ISSUE TITLE
Status Page (status.wire.com)

### ISSUE THREAD

**Issue by maltfield** [wireapp/wire#409]
This ticket is a request to create https://status.wire.com, which would display current & historic outages on the wire platform.

## Why?

Currently [Wire is down](https://github.com/wireapp/wire-webapp/issues/17239), and there is no way for users to check to see if this is a problem on their end or Wire's end (it's Wire's end -- their certificate returned for `app.wire.com` has expired)

## Additional Notes

The software that runs status.wire.com should run on external infrastructure, so that an outage of Wire's infrastructure doesn't cause an outage of the outage checker..

There should also be a prominent link to stauts.wire.com in the footer of wire.com with the text "System Status" or "System Uptime"

**Comment by b1pb1p** [comment]
We are now rolling out our status page for Wire Cloud, it is available at https://status.wire.com/

It automatically monitors the stats of Wire Cloud's various services to its users and customers.

We will also use it to communicate our plan maintenance windows and service evolutions. 

Thank you all for using and trusting Wire; we appreciate your interest and support.

**Comment by maltfield** [comment]
This is great, thank you!

It looks like the only thing that's missing, however, is a link to it.

@b1pb1p Any chance you can update the footer of your main website at wire.com to include a "System Status" link that points to status.wire.com?
