### ISSUE TITLE
Custom Device Name

### ISSUE THREAD

**Issue by BennySamir** [wireapp/wire#41]
Hello,

It would be nice to have the possability to change the device names. This make it easier to see which "Wire for Windows" is the private PC and which the work PC.
The name must be private and should not be displayed to others.

Thanks

**Comment by wmengli** [comment]
Thank you @BennySamir ! I've answered here https://github.com/wireapp/wire/issues/58
Closing this for now and feel free to contact us again for other questions.

Best wishes,
Wire Support Team
