### ISSUE TITLE
Conversation migration seemingly bricks account 

### ISSUE THREAD

**Issue by burdges** [wireapp/wire#410]
If you share the chat history from an old device to a new device, and then lose the old device, then you cannot delete the old device, and your contact's old messages go only to the new device.

There is afaik no way to resolve this problem.  Instead you must create a new account, and then find and ask each of yourt old contacts to remove your old account.

**Comment by burdges** [comment]
A wire device list should show this remove button:
![Screenshot_20240606-203034](https://github.com/wireapp/wire/assets/680126/956ef820-8e68-48f2-96a2-cf4797a2849e)

If the conversation history was transfered, then the device shows this screen without the remove button:
![Screenshot_20240606-202918](https://github.com/wireapp/wire/assets/680126/38a66d9e-c505-4f85-a8fc-c8ccd2573e4f)

There is now no way to remove the lost and possible compromized device.

**Comment by MohamadJaara** [comment]
Hi, thanks for the report. This issue should be resolved in our next release of v4.8.

**Comment by MohamadJaara** [comment]
the release is out, will close this one for now, please feel free to reopen it if not fixed
