### ISSUE TITLE
First Push Notification

### ISSUE THREAD

**Issue by BennySamir** [wireapp/wire#42]
Hello,

I have observed the following error in the last time:

- I'm working on a PC where Wire is installed und running in the Background
- If some one send me a message (first)
 - I hear a sound on my PC, but don't see any red dot or notification
 - The display on my iPhone flashes briefly, but no push notification is to be seen.
- If i answer the message, all new other messages works correct
 - Push Notification on PC and iPhone, and red dot on the wire icon (PC)
- If someone writes me again after a time, the same error occurs at the first message

I have reset the PUSH-Token on my iPhone, but have still the same issues.

Thanks

**Comment by david-wire** [comment]
Thanks for reporting and apologies for the delay in responding. What version of Windows are you using?

**Comment by BennySamir** [comment]
@david-wire i use Version 2.12.2729 in Windows and 2.35 (2825) in iOS

**Comment by david-wire** [comment]
OK - and Windows version (7, 8, 10...)?

**Comment by BennySamir** [comment]
Windows 10

**Comment by lucilacaranza** [comment]
HI @BennySamir,

Is the issue still happening ? We have pushed several fixes lately, could you please let me know what the status is on your end for this ?

Thanks,

**Comment by lucilacaranza** [comment]
HI again @BennySamir ,

I was wondering if you read my note from last week ?

Thanks,

**Comment by BennySamir** [comment]
Hi @lucilacaranza,

I'm currently in vacation. I can give you in 1-2 Weeks a Feedback.

Regards Benny

**Comment by BennySamir** [comment]
@lucilacaranza 
Now it's looks like that the bug is fixed.

THX

Regards Benny
