### ISSUE TITLE
[Feature Request] Music play volume during call

### ISSUE THREAD

**Issue by DOFfactory** [wireapp/wire#43]
[Copy, as requested by @helenakos, from https://github.com/wireapp/wire-desktop/issues/446#issuecomment-300114684]

This is an idea for enhancement. I often receive calls while listening to music, which then I have to pause manually. Both iMessages and Facetime have the option to mute/pause/lower the volume of music when a call occurs.

Personally, I prefer the lowering of the volume to +-10% of the volume of the call (similar to Facetime) rather than completely pausing the call (as iMessages behaves).

Would you consider such an option, maybe in settings?

**Comment by wmengli** [comment]
Hi @DOFfactory 

Thank you for the suggestion! This is not on our current roadmap, but we haven't ruled it out for the future. I am going to close this ticket for now and track it in our internal feature request system instead.

Best wishes,
Wire Support Team
