### ISSUE TITLE
Message distribution to multiple clients

### ISSUE THREAD

**Issue by sebastianbauer** [wireapp/wire#45]
Using Wire with multiple clients isn't fun if those aren't used frequently. I have some systems I use not so often. Opening Wire there is a mess of notifications. It's even worse when some very huge conversations must be updated on a mobile client.

**Comment by teller** [comment]
What's your expected / desired behavior?

**Comment by sebastianbauer** [comment]
That's pretty easy. A read message should be a read message. I don't want to see the unread message mark during loading old messages on another client.

Currently, the clients feel very independent and don't know about such states globally. It feels like conversations are replayed on other clients instead of updated to the current state.

**Comment by wmengli** [comment]
Hi @sebastianbauer 

Thank you for the suggestion and sorry for taking so long to reply. This is indeed something to improve but unfortunately not planned at this stage yet. We had done a small improvement for Android, not to "show" the calling history but it still took a while for client to finish the update. 

We will close this for now and add to our internal enhancement system. Meanwhile feel free to contact us again for other questions.

Best wishes,
Wire Support Team
