### ISSUE TITLE
[Suggestion] Add users by email, strip spaces

### ISSUE THREAD

**Issue by 2ge** [wireapp/wire#46]
Hi,

thanks for Wire, really nice. I would like to know, why when adding friend there is no possibility to search by email?

Also, for example if I know people name, I search like "John Doe" but it will not find "johndoe", I have to type "johndoe" to get some results. I think spaces should be stripped...

Thanks again

**Comment by david-wire** [comment]
Hello, thanks for the note. Whilst this used to be possible, we decided to remove search by email (for privacy related reasons) and you can now use usernames to search (as usernames are unique) for a specific user. 
Profile names, on the other hand, are not unique, hence why you have noticed this behavior indeed. I hope that clarifies the situation.

**Comment by sumyungguy** [comment]
Fyi, this support page still says you can search by e-mail:
https://support.wire.com/hc/en-us/articles/203878390-How-do-I-get-started-on-Wire-

**Comment by david-wire** [comment]
@sumyungguy thanks, well spotted, and updated.
