### ISSUE TITLE
Calls keep dying

### ISSUE THREAD

**Issue by bkeys** [wireapp/wire#48]
With the latest update calls keep on dying sporadically, it seems like you guys either have some bug on the server instance, or are restarting it often for maintenance. Do you guys have a clue why this is happening on the production server? Wire is not really usable in this state.

If you guys are undergoing maintenance I would suggest having a project blog and letting people know ahead of time if stuff like this is going to happen. This has been going on for the last 2 days.

If there is anything I can do to help investigating this let me know.

**Comment by david-wire** [comment]
Thanks for reporting.
We are not restarting the server(s) for maintenance. Do you hear some "beep" sounds for a while before the call drops? In that case that would indicate some packet loss / networking issues. 
We can keep looking into this issue if you have additional details to share (network connection quality, devices used, OS versions).

**Comment by bkeys** [comment]
The OS versions happen across different OS'es one of my friends runs OpenSuse, I run Fedora, and another friend runs Windows.
Network quality is not an issue, we have been using wire for months without this issue happening, there is no beep sound either, the call drops silent and then hangs up on it's own.
Does this perhaps happen when you have a large group (of say 8 people) and only 2 people pick up when you call the entire group, could that be causing issues?
Sorry I cannot give you any concrete info, if you need any log files just tell me where to find theme and I will post them here.

**Comment by david-wire** [comment]
> Does this perhaps happen when you have a large group (of say 8 people) and only 2 people pick up when you call the entire group, could that be causing issues?

That should not be the case.

> if you need any log files just tell me where to find theme and I will post them here.

Thanks, logs are useful, so you if you are using Wire for Web, you can open the browser console and type: `wire.app.enable_debugging()`. This will print quite a lot of lines so remember to disable it afterwards with `wire.app.disable_debugging()`.
If you are using the desktop apps, here is [how to open the console](https://github.com/wireapp/wire-desktop/wiki/Start-Parameters). This would apply to Windows and MacOS though.

**Comment by david-wire** [comment]
@bkeys Did you manage to gather some logs and/or does this issue still occur?
We'll close it for now, feel free to reopen if needed. Thanks!
