### ISSUE TITLE
phone number privacy & anonymity

### ISSUE THREAD

**Issue by sumyungguy** [wireapp/wire#49]
Does Wire get and process my phone number from my iPhone even if I don't explicitly share it?

When I signed up for my Wire account a few months ago, I used my e-mail. I did not give my phone number.

When I installed the Wire app on my iPhone a while later, I did not share my contacts. The next day, I got a contact request from someone I no longer wish to have contact with. This person has my phone number and e-mail in their contacts. I assume they received a notification that I had joined Wire. On what basis did that happen? My e-mail or my phone number?

I'd prefer that people not know my identity unless I specifically tell them. If I change my user name and e-mail address to something anonymous, will that prevent people from finding out my identity? Or would people who have my phone number still be notified that I signed up for Wire, and that my user name corresponds to that phone number?

**Comment by david-wire** [comment]
Thanks for the note.

> Does Wire get and process my phone number from my iPhone even if I don't explicitly share it?

No, we do not. 

>  I assume they received a notification that I had joined Wire. On what basis did that happen? My e-mail or my phone number?

We also do not notify users when someone who is in their address book joins Wire (no push notification or similar whatsoever). We do have an auto-connection mechanism, but that only applies when a phone number has been registered to a Wire account.
Please note that your username is unique and searchable, hence why you may have been found (on Wire) that way.

> If I change my user name and e-mail address to something anonymous, will that prevent people from finding out my identity? 

We have written about this topic [here](https://medium.com/@wireapp/staying-anonymous-on-wire-22faa13aba4d) (Staying anonymous on Wire).

**Comment by sumyungguy** [comment]
This was a person with whom I have not had any contact for more than a year, and who is not in contact with anyone else I know. There's no reason they would be searching for me on Wire, let alone happen to have done so just a day or so after I installed the app on my phone. Furthermore, I had a non-identifiable username.

It must have had something to do with my phone number or email being in their contact list. Perhaps not a push notification, but some indication that they might have seen while looking through their contact list. I don't see how there's any other explanation. Unfortunately I'm not in a position to ask them how they knew I was on Wire.

This happened some time ago. Maybe things have changed since then? When was the ability to search by e-mail address removed? Could that also be related to contact lists? In the "Staying anonymous on Wire" article you linked to, dated April 26th, it says you need to set up a new e-mail address and suggests Proton mail. Why does it say that, if it's not possible to find someone by their e-mail address?

I'm trying to figure out under what circumstances someone who has me in their contact list, and has shared it with Wire, would be able to find my Wire username, if I do not share my own contact list. I may be mistaken, but I'm still fairly certain that this actually happened.

Do I really need to use a fake e-mail address with Wire, and if I do, will that definitely prevent people who know my phone number from finding my Wire identity?
