### ISSUE TITLE
[Feature Request] Old soundcloud embed

### ISSUE THREAD

**Issue by ZerataX** [wireapp/wire#50]
I used to really like the old soundcloud embed, especially since I could even on mobile listen to songs while not leaving the app.
Is there any reason why it's gone?
I would greatly appreciate the old design.

**Comment by david-wire** [comment]
Thanks for the feedback, but this is due to design and technical implementation related reasons. 
We are not planning on rolling back to the previous design.
Thanks for taking the time to send us your comments.
