### ISSUE TITLE
PIN lock and/or fingerprint lock

### ISSUE THREAD

**Issue by edgren** [wireapp/wire#51]
This feature is highly needed for higher security for your account/application. Please, add it!

**Comment by david-wire** [comment]
This is already implemented on iOS. I am assuming you are using an Android device?

**Comment by edgren** [comment]
Oh. I didn't know that. Yes. I want that function for the Android version. Why hasen't it been added to the Android version yet?

**Comment by david-wire** [comment]
This is on our roadmap, but no ETA as of yet. In the meantime, we can close this issue and you can follow up on https://github.com/wireapp/wire-android/ instead.
