### ISSUE TITLE
Provide a 1-week option for disappearing messages timer

### ISSUE THREAD

**Issue by sptankard** [wireapp/wire#52]
Please implement a 1-week timer duration in addition to the existing options (which max out at 1 day).

We're using Wire as a messaging solution for an organization, where we desire both end-to-end encryption and ephemeral features. However, the 1-day max limit is too short for many purposes. An additional 1 week option is much more practical and would greatly improve the utility of Wire (Signal already implements a 1-week option).

**Comment by wmengli** [comment]
Hi @sptankard 

Thanks for the suggestion! We might change it in the future but no ETA yet as we are working on other priorities at the moment. 
I am going to close this ticket for now and track it in our internal feature request system instead.

Best wishes,
Wire Support Team
