### ISSUE TITLE
Make disappearing-message timer apply per-conversation, not per-sender  

### ISSUE THREAD

**Issue by sptankard** [wireapp/wire#53]
This is the method used by Signal. It is conceptually simpler and more predictable, and allows to more easily avoid unintentional leakage of messages (that is, "leakage" out of ephemeral mode into permanent-stored mode).

This is particularly useful when using messaging groups with large numbers of members.

**Comment by wmengli** [comment]
Hi @sptankard 
This is how timed message work now - per conversation and not by per sender. Is it working differently for you? If so, can you tell us a bit more so we can investigate? Please let us know the platform, Wire version, and  steps to reproduce so that we can troubleshoot for you. Thanks!

**Comment by wmengli** [comment]
Hello, we are closing this ticket for now. Feel free to reopen if needed or contact us for other questions.

Best wishes,
Wire Support Team
