### ISSUE TITLE
Ability to remove/delete contacts/conversations/devices completely

### ISSUE THREAD

**Issue by Larx** [wireapp/wire#55]
In all Wire apps I'm currently missing the option to remove contacts/conversations/devices completely. Currently you can only archive them.

- I cannot remove devices I don't own any more, or on which I had to reinstall Wire.
- I'm not interested in Otto the Bot anymore.
- Not everyone in my address book Wire found as owning a Wire account is relevant for me. But once they're in my Wire contact list, I can no longer get rid of them.
- When trying out Wire, I created/deleted/recreated accounts with the same name. I cannot get rid of the old, not-more-exisiting contacts under the same name.
- All those archived contacts again pop up when sharing something with the Android app, and completely mess up the list.

etc. etc. etc.

**Comment by david-wire** [comment]
Thanks for your comments.

> I cannot remove devices I don't own any more, or on which I had to reinstall Wire.

You should be able to. Wire will ask you to enter your password to do so.

> I'm not interested in Otto the Bot anymore.

You can simply mute and delete the history of that conversation.

> But once they're in my Wire contact list, I can no longer get rid of them.

Correct, you cannot disconnect from an existing connection, only block / archive that connection.

> All those archived contacts again pop up when sharing something with the Android app, and completely mess up the list.

This is something we could improve, thanks for the feedback.

**Comment by teller** [comment]
@Larx The "lifehack" is to block unwanted contacts. Hides them completely from sharing menus etc.

**Comment by Larx** [comment]
Is there a deeper reason why delete functionality is not implemented and you have to block contacts instead? I mean, the GUI offers a delete function, but that does not really do what I'd expect it to do.

IMHO this is a basic functionality missing!

As I tried a bit around when setting up contacts, I created, deleted and recreated accounts. However, the old ones are still somehow there and are easily mixed up with the active ones.

**Comment by teller** [comment]
It's just an architecture decision made years ago that has served us reasonably well so far (judging by the amount of feedback, or lack of it). This does not mean we're not open to revisiting these choices (or any choices) as Wire grows and user patterns change.

**Comment by Larx** [comment]
I would vote to enable real deleting, please. See e.g. the problem with deleted accounts and so on.

**Comment by Namnodorel** [comment]
How about a middle-way? The "delete"-Option could be renamed to "remove", or something less specific with a popup asking whether you want to permanently delete or just archive that conversation.

**Comment by Larx** [comment]
Maybe. Doesn't matter how, I find it really annoying to lack "delete" options....

**Comment by wmengli** [comment]
Hi all, thanks again for sharing your feedback. 

We are keeping the delete function as it as now, but we haven't ruled it out for the future.
I am going to close this ticket for now and track it in our internal feature request system instead.

Best wishes,
Wire Support Team

**Comment by cardassian-tailor** [comment]
the inability to actually delete contacts is super super annoying.

**Comment by cardassian-tailor** [comment]
"add me to the chat" becomes a nightmare ... when you start connecting to hundreds of users that you cant actually delete.

**Comment by cardassian-tailor** [comment]
It would be awesome if someone could confirm, briefly, how this is occuring in the backend because maybe this would give us an idea as to why this path was originally chosen. 

I'm assuming it has to do with the key structure. If you connect with a user and exchange public keys, I guess the only way to unconnect with them would be to revoke that old key pair, generate a new private/public key pair and exchange it with all of your current contacts except those you just deleted. Is this fairly accurate ?

**Comment by teller** [comment]
Not sure if @tiago-loureiro has time to go into these details but as stated before - there are currently no plans to change this behavior. We'll invest our time into productivity and business features for now to ensure a healthy business model that helps to sustain the free, personal version.

**Comment by txVLN** [comment]
> It's just an architecture decision made years ago that has served us reasonably well so far (judging by the amount of feedback, or lack of it). This does not mean we're not open to revisiting these choices (or any choices) as Wire grows and user patterns change.

Well here's some feedback and I doubt I'm the only one:

Installed app, created account, allowed access to contacts. Huge mistake apparently, who knew. Now the only people in my contact list are ones I have no idea who they are, they're now texting me to say hello and talk about their conspiracy theories, and I'm going to have to see their name from now on every time I want to look at my contacts. Guess what? Uninstalled.

Sometimes people like to use things differently than you do. If that's a problem, fine. But that means you're cutting out a huge part of your potential user base. Your calls.

**Comment by Aikatsui** [comment]
https://github.com/wireapp/wire-webapp/issues/11198 https://github.com/wireapp/wire/issues/206

**Comment by burdges** [comment]
> >  I cannot remove devices I don't own any more, or on which I had to reinstall Wire.
> You should be able to. Wire will ask you to enter your password to be able to do so.

This is false @david-wire 

If you share the chat history from an old device to a new device, and then lose the old device, then you cannot delete the old device, and your contacts old messsages go only to the new device.

There is afaik no way to resolve this problem.  Instead you must create a new account, and then find and ask each of yourt old contacts to remove your old account.
