### ISSUE TITLE
[Feature Request] IP voice calls for regular phone contacts (unencrypted) 

### ISSUE THREAD

**Issue by clessley** [wireapp/wire#56]
Make voice IP/cellular network calls to non-Wire contacts (and thus set Wire as default dialer/messenger application).

A use case example: 

1. [Encrypted] call to client [on Wire] to schedule a meeting time.
2. [Unencrypted] call a pizza place [not on Wire] to order lunch.

Signal already provides this feature.

**Comment by david-wire** [comment]
Thanks for the feedback and for the suggestion. However, we are not planning on implementing this.

**Comment by clessley** [comment]
So sad, as Wire is superior in every other way. Appreciate the quick feedback and respect the decision.
