### ISSUE TITLE
Feature-Request: Device-List with names

### ISSUE THREAD

**Issue by user9209** [wireapp/wire#58]
Hello together,

as I have too much devices (see #57) and must remove one if I logged in a device,
it would be nice to set a name for each device as the current IDs like " AA BB CC DD EE FF"
are not human readable to differ the devices.

So the ability to set a name would be nice.
Also a time stamp "last seen" of the device would allow you to remove the oldest device.

Thanks in advance

**Comment by BennySamir** [comment]
Duplicate #41

**Comment by wmengli** [comment]
Hi!

Thank you for the feedback. We are looking into different options how to simplify this but no ETA at the moment. Something in our roadmap so please stay tuned!

I am closing this for now and feel free to contact us again for other questions.

Best wishes,
Wire Support Team
