### ISSUE TITLE
additional security features for Wire to secure account

### ISSUE THREAD

**Issue by oscalation** [wireapp/wire#59]
If i'm not mistaken, all one needs currently is my email address and wire password to login to my account. I would like to suggest a second security measure. 

1. Maybe an optional pin code that is required to unlock the app this is required to be used when the app is first installed. A password reset should not reset this second pin code, obviously. 

2. Maybe a master key that is required to be typed in when the application is used on a new device (this doesnt require tracking of user devices) 

3. When a password reset occurs, im assuming the prior encryption keys change so ALL prior communications should be lost/irrecoverable to the user upon logging in with the new password.

4. Delayed responses should be default behavior. When a password reset request occurs, the process should NOT be immediate. It should take, lets say as an example, 24 hours. During this waiting period the user should be notified by any means necessary = "password reset in progress, login to cancel this request"   ... giving yet another method to stop an attack. 

Regardless, we need some additional security measures from the authentication side.

**Comment by raphaelrobert** [comment]
Thanks for the suggestions!

1. This is already the case with the iOS client, Android will follow.
2. Something similar is on our todo list.
3. The encryption keys are rotated constantly, regardless of a password reset.
4. This would be a possibility.

**Comment by wmengli** [comment]
Hi, we will close this for now. Feel free to contact us for other questions. 
Thanks!

Best wishes,
Wire Support Team
