### ISSUE TITLE
Cannot login on mobile app with web created account, and vice-versa

### ISSUE THREAD

**Issue by SkyzohKey** [wireapp/wire#60]
Hey guys.

I created an account from my computer _(Linux - Solus OS, Wire AppImage 64 bits)_ and then tried to login on the Android app _(Android 7.1.1 - Honor 8)_ using that same account. But it fails.

The mobile app tells me that error message:

> **Invalid information**
> Please verify your credentials and try again.

I verified my credentials and they ARE valid, but the app think they are not. The same issue works for mobile created account when i try to connect on my desktop app.

That's a really weird issue and it undermine my Wire usage... Please investigate. Anyway, thanks for the **great** solution you provide!

**Comment by wmengli** [comment]
Hi @SkyzohKey , we will close this as referred to https://github.com/wireapp/wire-webapp/issues/1467

Best wishes,
Wire Support Team
