### ISSUE TITLE
Feature request : automatic answer 

### ISSUE THREAD

**Issue by unrealwill** [wireapp/wire#61]
Redirected here by [ https://github.com/wireapp/wire-desktop/issues/698#issuecomment-312294620 ]
Redirected to github by [Wire Support]

This is for Linux (not selectable in the Platform box below).

I need to be able to automatically start video conversation when called.
Currently I use skype 4.3 linux, it allows my contacts (and only them) to automatically see/hear my video when they call. Skype is retiring and I need a substitute.

How can I achieve this with wire?

**Comment by wmengli** [comment]
Hi @unrealwill , thanks for the suggestion. Not in the roadmap but we might revisit when we receive more request like this :)

**Comment by wmengli** [comment]
We've discussed this within our team and decided to track it in our internal system. 
We will close it for now, feel free to contact us again for other questions.

Thanks!

Best wishes,
Wire Support Team
