### ISSUE TITLE
Group Chat Topics

### ISSUE THREAD

**Issue by 0xdade** [wireapp/wire#62]
It'd be really great if we could set a topic for a group chat, to pin valuable information in the chat.  irc has topics, slack has topics, etc :) Topics are useful for group chat rooms.

**Comment by wmengli** [comment]
Hi @0xdade , thanks for the suggestion. Not in the roadmap yet but we might revisit when we receive more request like this :)

**Comment by wmengli** [comment]
We will close this for now. Just want to let you know we did not forget about it, it's tracked in our internal feature request system. Whenever someone has similar request, it's counted +1 :)

Feel free to contact us again for other questions.

Best wishes,
Wire Support Team
