### ISSUE TITLE
The ability to reply to a specific message

### ISSUE THREAD

**Issue by 0xdade** [wireapp/wire#63]
When replying in a group chat, you may want to reply to something that happened several messages ago, maybe even tens or hundreds of messages ago. It'd be nice if you could choose to reply to a specific message and it would include a snippet of that message or whatever so that everyone knew the context of your response. Slack has this via the "share message" feature. Telegram has it via the "reply" feature when you click on a specific message.

Just another thing to make group chats more effective :)

**Comment by Namnodorel** [comment]
In other words, quotes :D
I think the easiest way to solve this is a "Quote" or "Reply"-Button next to each message, that automatically pastes the content of the message into the input field, together with a new sort of formatting that shows that this message is a quote (I think the way most other messengers solve this is by simply putting a ">" in front of the line that shall be quoted - well, even GitHub uses that...)

**Comment by wmengli** [comment]
Hi @0xdade and @Namnodorel , thanks for the suggestion. This is one of the frequent request we received :) 
It's in our feature list but no plan to implement at the moment. 
We will close this for now and it's counted +1 in our internal feature request system. Can't promise anything but we might revisit when we have time. Feel free to contact us for other questions.

Thanks!

Best wishes,
Wire Support Team

**Comment by eknoes** [comment]
Is there an update on this, is it planned for the near future?

**Comment by idchlife** [comment]
Interested in this as well.

**Comment by MatthiasBergen** [comment]
this functionality would be really helpful.

**Comment by tamazov** [comment]
+1

**Comment by 0xdade** [comment]
Hey look they implemented on web today :)
