### ISSUE TITLE
Feature: Option to change name format or rename user

### ISSUE THREAD

**Issue by rehoehle** [wireapp/wire#64]
I use Wire now and i find that it's working well and and try to change with all of my contacts.

But one thing what i've seen is that my contact list have only the firstname of the user. That is a problem if some users have the same name and i can't change them. Some user Don't use their complete name or use a pseudonyms what makes it hard to see which user is the right one.

It would be very helpful if i could rename a user or set as option that i can see the username instead of the firstname.

**Comment by wmengli** [comment]
@rehoehle Thanks for the suggestion! This is in our feature request list and we acknowledge that this is helpful for users. However it's not planed for the near future release yet. We will be looking into more contact management options :)

We will close this for now and feel free to contact us again for other questions.

Best wishes,
Wire Support Team
