### ISSUE TITLE
Feature request : Ability to quote a message

### ISSUE THREAD

**Issue by SkyzohKey** [wireapp/wire#65]
Hey guys,

This feature request is about the implementation of the ability to quote a message. 

ie. You would click the 3 dots beside the message and in the dropdown you can click « Quote ». Then, Wire would pre-fill the input with the `> ${message}\n`.

Of course, the quoted messages should be stylized differently from a normal message.

Something like the following:

----

> This is a cool message and it lives in a quote.  

This is the answer to the previously quoted message. ;)

**Comment by Namnodorel** [comment]
Have a look at #63

**Comment by wmengli** [comment]
@SkyzohKey Thanks for the suggestion. Yes, this is one of the frequent request :)
Sorry to tell you that we will close this for now, but it's counted +1 for that request in our internal feature tracking system. 

Feel free to contact us again for other questions.

@Namnodorel thank you for linking to #63 !

Best wishes,
Wire Support Team
