### ISSUE TITLE
Registration not working on Ubuntu Aquaris BQ

### ISSUE THREAD

**Issue by XeniaGabriela** [wireapp/wire#7]
The app is available in the ubuntu app store. When opening it after the download, in the registration process, the checkbox for accepting the terms and conditions can't be clicked. It always opens the terms and conditions page with no possibility to return to the registration page. Even when I tried to match the checkbox with a touchpen, the checkbox was not checked.

**Comment by teller** [comment]
Sorry, Wire is currently not developed for, nor tested, on Linux-based tablets.

**Comment by wmengli** [comment]
Sorry, as @teller pointed out this is currently not supported. 
Thank you for taking the time to send us your comments, and please feel free to contact us again if you have additional questions. 

Best wishes,
Wire Support Team
