### ISSUE TITLE
Explanation on how Wire syncs messages on different devices

### ISSUE THREAD

**Issue by Sattar1** [wireapp/wire#70]
Hello.

AFAIK, end to end encryption (E2EE) initiates on one device (one platform e.g. android), message reaches the destination and decrypts there. So other devices of mine (like iOS or web client) don't have keys to decrypt the message.

But Wire provides multi platform E2EE instant messaging, storing chat history.

The question is: How do different devices decrypt a message that is end to end encrypted on a different device? How do iOS and Android and web and desktop client sync messages?! If they share private keys, how can we trust the server not to save the key?! (As the server code is not completely open source till now).

Thanks for the great app.

**Comment by Namnodorel** [comment]
I'm by no means an encryption expert or have deep knowledge of how Wire works, in group chats or when you use an account with multiple devices, each time a new device is added, a new key is generated for every participant of the conversation. That is also why it is not possible to see messages sent before your account/device joined into a group/conversation. That way the key doesn't need to be stored on the server, or shared with new participants/devices and still remains secure..

**Comment by raphaelrobert** [comment]
@Namnodorel's explanation is correct! The private keys never leave the devices, a new one is generated on every device you add. Messages are encrypted individually for every device.

There is a more in depth explanation in our whitepapers, which you can find here:[ wire.com/privacy]( wire.com/privacy).

**Comment by Sattar1** [comment]
Thanks @Namnodorel  and @raphaelrobert for the replies.

Is there any way to check this out in the code? Anyone has audited this specific issue?
So, imagine I have 4 clients (android, iOS, desktop, web). My contact has logged in 4 clients too.

As you said, whenever I send a normal message (Not a timed message), it is encrypted 4 times with 4 different keys to reach my contact, also is encrypted 3 times with 3 different keys to reach my different devices. right?!

Furthermore, what happens to "timed messages"? Please provide above situation for a timed message. Since they are not shown in different devices of mine, what happens to them?

Thanks.

**Comment by raphaelrobert** [comment]
1. Feel free to look at the code, https://github.com/wireapp/wire-ios, https://github.com/wireapp/wire-android and https://github.com/wireapp/wire-webapp.
There is a code audit of the encryption [here](https://wire.com/en/privacy/#audits) and there will be a full audit of all code later this year.

2. Correct.

3. The encryption is the same for the devices of your contact, but timed messages are not sent to your own devices.

**Comment by Sattar1** [comment]
Thanks @raphaelrobert . So let's close the topic since the issue is solved 👍
