### ISSUE TITLE
Feature request: SMS, default SMS app on mobile

### ISSUE THREAD

**Issue by SamErde** [wireapp/wire#71]
It would be great if SMS handling could be added to Wire, and allow it to be set as the default SMS/MMS app [on Android]. (Like Signal.) It would be much more convenient, and would also help greatly with adoption, as people would have incentive to use it even if not many of their contacts are using it yet.

**Comment by lucilacaranza** [comment]
Hello,

Thanks for your suggestion, I will relay it to all teams.
Thanks,

**Comment by u5893405** [comment]
I do not use Signal and anything that works similar and bound to SMS and phone numbers, but I'm against that, if it will require SMS permission by default in fresh installation.
That should be only opt-in.
Non-tech people will confuse it with SMS, Wire isn't created for that.
If someone could not even comprehend how to use "new unfamiliar" software but not their "old good SMS",  it's their problem, not of users who specifically have chosen Wire for security.

**Comment by SturdyErde** [comment]
I can certainly appreciate that perspective and agree that making it a manual opt-in setting after installation would be the preferred action.
