### ISSUE TITLE
feature request: conversations history

### ISSUE THREAD

**Issue by weechman** [wireapp/wire#75]
hi,
i created this over on the desktop app issues page, then saw a comment about posting feature requests here, instead. so i am.

i am not including wire versions of platforms since it is across versions and platforms.
i was thinking that not having the conversation history automatically saved would be a nice feature, and maybe providing it as a toggle option in preferences.
this is just a personal preference issue for me. when i reboot, i don't like or need to have the conversations saved.

**Comment by weechman** [comment]
i should probably clarify that i am talking about when the app is restarted, with or without device reboot.

**Comment by lucilacaranza** [comment]
Hey,

Thanks for writing. 
Interesting suggestion, although I must mention most users are requesting a 'history backup' feature.
I will share your input with our teams.
Best,

**Comment by weechman** [comment]
actually, i think i just answered my own question.
i can create another account and keep the phone conversations separate from the desktop ones, which is ultimately the point of my request to not keep the conversation history when the app is shut down/reboot.

you can close this, if you want. it was circuitous, but i have a solution :)

thanks!!
