### ISSUE TITLE
Be able to answer a message in the conversation

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire#76]
In group message, the discussion can devellop fast and sometimes a user need to answer an old message in it.

It could improve the user exprience to pick a previous message and choose to answer it. When the new message is posted, a summary of the original message is tied-up close to the new one. That way, all participant would know what the new message is related to.

**Comment by lucilacaranza** [comment]
Hey!

Noted! I must say this is a very requested featured.
Keep those suggestions coming.
Best,

**Comment by violoncelloch** [comment]
yes, I'd also like a way to refer to a previous message! not only in group chats but also in normal 1:1 chats...

**Comment by ehodzic** [comment]
Basically, a **quote** feature is very much needed.
Currently, the markdown (https://support.wire.com/hc/en-us/articles/115002676029-How-can-I-use-markdown-to-format-text-on-Wire-) does not support any kind of quotation formatting.

**Comment by manowicz** [comment]
Being able to quote part of the message instead of just replying to it would be highly appreciated. In my personal experience of using Wire long, multi-threaded messages are exchanged between users rather than multiple short messages.

**Comment by lucilacaranza** [comment]
Thread replies have been released last week across all platforms :)

https://support.wire.com/hc/en-us/articles/360000587698-How-can-I-directly-reply-to-a-message-

**Comment by manowicz** [comment]
> Thread replies have been released last week across all platforms :)

It's great, thank you!
Are you considering adding any way of quoting only a part of the message – e.g. by replying to a text selection, or being able to edit the body of the message being quoted before sending it?

**Comment by IpsmLorem** [comment]
Is it planned to be able to quote timed messages as well ? (like signal)
