### ISSUE TITLE
Timed message available times

### ISSUE THREAD

**Issue by Tuj3Bz90dV** [wireapp/wire#89]
This is a very simple feature request to extend the available times in timed messages. Currently there is a sharp jump from 5 minutes to 1 day. 

1 day seems excessive for a temporary conversation, but 5 minutes seems like too little time. If I want to go over a conversation I just had, for example, half of it might be already gone by the time I'm done with it. I therefore would add some extra possible times to that list. 1 hour seems like a reasonable addition.

**Comment by richpersaud** [comment]
Agreed on addition of a 1 hour time.   Would be useful for Wire to document example use cases for the existing timers, if there's a need to drop one of these in exchange for adding the 1 hour timer.  

5s
15s
30s
1m
5m
1d

What timers are available in competing apps?

**Comment by teller** [comment]
@Yorgos-V @bennyn @mikeger @hakonbo @deanrobertcook 

We're seeing quite a lot of requests for something between 5m and 1d. Adding 1 hour makes sense. 

Low prio.

**Comment by labdsf** [comment]
Please add 1 week (1w). It is available both in Telegram and Signal.

**Comment by mark-franz** [comment]
I would also vote for 1 week. 
1 day can be too short for users who don't use their smartphone everyday. (Yes, those user groups exist ... :-) )
1 day is also too short if you want to follow up on something that you talked about just two days ago. 
I feel 1 week can be just right to get rid of too many old messages, but still be able to refer to messages "just sent". 
(Some people are just "slower", they've got longer rhythms in what they're doing. imo an app for everyone should reflect that. )

**Comment by libBletchley** [comment]
I use 1 day as a way to keep a clean history, but it's too short.  Someone sees my msg while driving or doing something with interruptions, then they have just 1 day to followup.  That's not reasonable.

It's also strange that there all those micro steps (5 sec, 15 sec, 30 sec, etc). Those should be simplified down to a few, and replaced with:

* 1 week
* 1 month

**Comment by teller** [comment]
@libBletchley We'll have news about this shortly - probably already next week.

**Comment by Tuj3Bz90dV** [comment]
Forgot about this ticket. I'm personally satisfied with the current options, so I'm closing this.
