### ISSUE TITLE
I've found a bug in pc(windows) version of the programm

### ISSUE THREAD

**Issue by FixerLT** [wireapp/wire#9]
During a call, i found out that screen sharing works properly only if person, who shares, is the one, who called. So one of two can share his screen, while another one only shows black screen instead of sharing.

**Comment by mykola-mokhnach** [comment]
Can you please provide more details on the report? What is the client/OS version? Which is client is used by the second client? What type of call it was - video or audio?

**Comment by david-wire** [comment]
@FixerLT closing this for now, please contact support via https://support.wire.com/hc/en-us/requests/new if you want us to follow up.
